const CONTENT_SERVICE_API_URL = process.env.NEXT_PUBLIC_CONTENT_SERVICE_API_URL;
const DIALOGUE_SERVICE_API_URL = process.env.NEXT_PUBLIC_DIALOGUE_SERVICE_API_URL;

if (!CONTENT_SERVICE_API_URL) throw new Error('NEXT_PUBLIC_CONTENT_SERVICE_API_URL is not set');
if (!DIALOGUE_SERVICE_API_URL) throw new Error('NEXT_PUBLIC_DIALOGUE_SERVICE_API_URL is not set');

export const contentBackendURL = CONTENT_SERVICE_API_URL;
export const dialogueBackendURL = DIALOGUE_SERVICE_API_URL;