export enum DialogueDirectionEnum {
    // General conversation flow
    CONVERSATION_FLOW__END_DIALOGUE = "CONVERSATION_FLOW__END_DIALOGUE",
    CONVERSATION_FLOW__CONTINUE_TOPIC = "CONVERSATION_FLOW__CONTINUE_TOPIC",
    CONVERSATION_FLOW__CHANGE_TOPIC_MINIMALLY = "CONVERSATION_FLOW__CHANGE_TOPIC_MINIMALLY",
    CONVERSATION_FLOW__CHANGE_TOPIC_SIGNIFICANTLY = "CONVERSATION_FLOW__CHANGE_TOPIC_SIGNIFICANTLY",

    // Emotional and tone control
    EMOTIONAL_CONTROL__CALM_COUNTERPART = "EMOTIONAL_CONTROL__CALM_COUNTERPART",
    EMOTIONAL_CONTROL__PROVOKE_COMBAT = "EMOTIONAL_CONTROL__PROVOKE_COMBAT",
    EMOTIONAL_CONTROL__CREATE_TENSION = "EMOTIONAL_CONTROL__CREATE_TENSION",
    EMOTIONAL_CONTROL__CREATE_HARMONY = "EMOTIONAL_CONTROL__CREATE_HARMONY",
    EMOTIONAL_CONTROL__FLATTER_COUNTERPART = "EMOTIONAL_CONTROL__FLATTER_COUNTERPART",
    EMOTIONAL_CONTROL__INSULT_COUNTERPART = "EMOTIONAL_CONTROL__INSULT_COUNTERPART",
    EMOTIONAL_CONTROL__AMUSE_COUNTERPART = "EMOTIONAL_CONTROL__AMUSE_COUNTERPART",
    EMOTIONAL_CONTROL__APOLOGIZE = "EMOTIONAL_CONTROL__APOLOGIZE",
    EMOTIONAL_CONTROL__GAIN_SYMPATHY = "EMOTIONAL_CONTROL__GAIN_SYMPATHY",

    // Motivations and goals
    MOTIVATIONS_AND_GOALS__PURSUE_UNFULFILLED_GOALS = "MOTIVATIONS_AND_GOALS__PURSUE_UNFULFILLED_GOALS",
    MOTIVATIONS_AND_GOALS__DISTRACT_FROM_PLAYER_GOALS = "MOTIVATIONS_AND_GOALS__DISTRACT_FROM_PLAYER_GOALS",
    MOTIVATIONS_AND_GOALS__OBTAIN_INFORMATION = "MOTIVATIONS_AND_GOALS__OBTAIN_INFORMATION",
    MOTIVATIONS_AND_GOALS__SHARE_INFORMATION = "MOTIVATIONS_AND_GOALS__SHARE_INFORMATION",
    MOTIVATIONS_AND_GOALS__BARGAIN_OR_TRADE = "MOTIVATIONS_AND_GOALS__BARGAIN_OR_TRADE",
    MOTIVATIONS_AND_GOALS__SEEK_ALLIANCE = "MOTIVATIONS_AND_GOALS__SEEK_ALLIANCE",
    MOTIVATIONS_AND_GOALS__UNDERMINE_ALLIANCE = "MOTIVATIONS_AND_GOALS__UNDERMINE_ALLIANCE",
    MOTIVATIONS_AND_GOALS__GAIN_TRUST = "MOTIVATIONS_AND_GOALS__GAIN_TRUST",
    MOTIVATIONS_AND_GOALS__EXPLOIT_TRUST = "MOTIVATIONS_AND_GOALS__EXPLOIT_TRUST",

    // Subterfuge and manipulation
    SUBTERFUGE_AND_MANIPULATION__LIE_AND_MANIPULATE = "SUBTERFUGE_AND_MANIPULATION__LIE_AND_MANIPULATE",
    SUBTERFUGE_AND_MANIPULATION__TELL_HALF_TRUTHS = "SUBTERFUGE_AND_MANIPULATION__TELL_HALF_TRUTHS",
    SUBTERFUGE_AND_MANIPULATION__CONFRONT_LIES = "SUBTERFUGE_AND_MANIPULATION__CONFRONT_LIES",
    SUBTERFUGE_AND_MANIPULATION__TRICK_OR_DECEIVE = "SUBTERFUGE_AND_MANIPULATION__TRICK_OR_DECEIVE",
    SUBTERFUGE_AND_MANIPULATION__EXPOSE_TRUTH = "SUBTERFUGE_AND_MANIPULATION__EXPOSE_TRUTH",

    // Conflict and combat
    CONFLICT_AND_COMBAT__INITIATE_COMBAT = "CONFLICT_AND_COMBAT__INITIATE_COMBAT",
    CONFLICT_AND_COMBAT__DEFUSE_COMBAT = "CONFLICT_AND_COMBAT__DEFUSE_COMBAT",
    CONFLICT_AND_COMBAT__INTIMIDATE_COUNTERPART = "CONFLICT_AND_COMBAT__INTIMIDATE_COUNTERPART",
    CONFLICT_AND_COMBAT__CHALLENGE_COUNTERPART = "CONFLICT_AND_COMBAT__CHALLENGE_COUNTERPART",

    // Social dynamics
    SOCIAL_DYNAMICS__ESTABLISH_DOMINANCE = "SOCIAL_DYNAMICS__ESTABLISH_DOMINANCE",
    SOCIAL_DYNAMICS__SUBMIT_TO_COUNTERPART = "SOCIAL_DYNAMICS__SUBMIT_TO_COUNTERPART",
    SOCIAL_DYNAMICS__FIND_COMMON_GROUND = "SOCIAL_DYNAMICS__FIND_COMMON_GROUND",
    SOCIAL_DYNAMICS__EXCLUDE_COUNTERPART = "SOCIAL_DYNAMICS__EXCLUDE_COUNTERPART",
    SOCIAL_DYNAMICS__INCLUDE_COUNTERPART = "SOCIAL_DYNAMICS__INCLUDE_COUNTERPART",

    // Moral alignment
    MORAL_ALIGNMENT__APPEAL_TO_VIRTUE = "MORAL_ALIGNMENT__APPEAL_TO_VIRTUE",
    MORAL_ALIGNMENT__APPEAL_TO_VICE = "MORAL_ALIGNMENT__APPEAL_TO_VICE",
    MORAL_ALIGNMENT__ENCOURAGE_SELFISHNESS = "MORAL_ALIGNMENT__ENCOURAGE_SELFISHNESS",
    MORAL_ALIGNMENT__ENCOURAGE_SELFLESSNESS = "MORAL_ALIGNMENT__ENCOURAGE_SELFLESSNESS",

    // Other creative options
    OTHER_CREATIVE_OPTIONS__TELL_A_STORY = "OTHER_CREATIVE_OPTIONS__TELL_A_STORY",
    OTHER_CREATIVE_OPTIONS__USE_HUMOR = "OTHER_CREATIVE_OPTIONS__USE_HUMOR",
    OTHER_CREATIVE_OPTIONS__USE_POETRY = "OTHER_CREATIVE_OPTIONS__USE_POETRY",
    OTHER_CREATIVE_OPTIONS__USE_RIDDLES = "OTHER_CREATIVE_OPTIONS__USE_RIDDLES",
    OTHER_CREATIVE_OPTIONS__USE_SILENCE = "OTHER_CREATIVE_OPTIONS__USE_SILENCE",
    OTHER_CREATIVE_OPTIONS__DIVERT_ATTENTION = "OTHER_CREATIVE_OPTIONS__DIVERT_ATTENTION",

    // Nonverbal communication
    NONVERBAL_COMMUNICATION__REMAIN_SILENT = "NONVERBAL_COMMUNICATION__REMAIN_SILENT",
    NONVERBAL_COMMUNICATION__INTENTIONALLY_IGNORE = "NONVERBAL_COMMUNICATION__INTENTIONALLY_IGNORE",
    NONVERBAL_COMMUNICATION__DISMISSIVELY_IGNORE = "NONVERBAL_COMMUNICATION__DISMISSIVELY_IGNORE",
    NONVERBAL_COMMUNICATION__THOUGHTFUL_SILENCE = "NONVERBAL_COMMUNICATION__THOUGHTFUL_SILENCE",
    NONVERBAL_COMMUNICATION__CONTEMPLATIVE_SILENCE = "NONVERBAL_COMMUNICATION__CONTEMPLATIVE_SILENCE",
    NONVERBAL_COMMUNICATION__DEFIANT_SILENCE = "NONVERBAL_COMMUNICATION__DEFIANT_SILENCE",
    NONVERBAL_COMMUNICATION__RESPECTFUL_SILENCE = "NONVERBAL_COMMUNICATION__RESPECTFUL_SILENCE",
    NONVERBAL_COMMUNICATION__AWKWARD_SILENCE = "NONVERBAL_COMMUNICATION__AWKWARD_SILENCE",
}