version: '3.8'

services:

  server:
    build:
      context: ./backend/ai-service
    environment:
      - ROLE=server
    command: python3 server.py
    ports:
      - "50051:50051"
    depends_on:
      - redis

  ai-service-worker:
    build:
      context: ./backend/ai-service
    environment:
      - ROLE=worker
    command: python3 worker.py
    ports:
      - "50052:50052"
    depends_on:
      - redis

  # Backend Proto Generation Service
  backend-proto-generator:
    image: node:18
    container_name: backend_proto_generator
    working_dir: /usr/src/app
    volumes:
      - ./backend/content-service:/usr/src/app
    command: sh -c "npm install && npm run proto:generate"
    profiles:
      - backend
      - fullstack
    depends_on:
      - world-db
      - campaign-db

  # Backend Microservices
  content-service:
    build:
      context: ./backend/content-service
      dockerfile: Dockerfile.dev
    container_name: content_service
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    ports:
      - "50051:50051"
    environment:
      - NODE_ENV=development
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_HOST__WORLD=world-db
      - DATABASE_PORT__WORLD=5432
      - DATABASE_NAME__WORLD=${POSTGRES_DB__WORLD}
      - DATABASE_HOST__CAMPAIGN=campaign-db
      - DATABASE_PORT__CAMPAIGN=5432
      - DATABASE_NAME__CAMPAIGN=${POSTGRES_DB__CAMPAIGN}
      - DATABASE_SYNCHRONIZE=false
    volumes:
      - ./backend/content-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - world-db
      - campaign-db
      - backend-proto-generator
    profiles:
      - fullstack
      - backend

  # Envoy Proxy
  envoy:
    image: envoyproxy/envoy:v1.22.0
    container_name: envoy_proxy
    restart: always
    ports:
      - "8080:8080" # HTTP endpoint for frontend
      - "9901:9901" # Admin interface (optional)
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy/envoy_access.log:/var/log/envoy/envoy_access.log
    depends_on:
      - content-service
    profiles:
      - fullstack

  # Databases
  world-db:
    image: postgres:14
    container_name: world_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB__WORLD}
    ports:
      - "55433:5432"
    volumes:
      - world_db_data:/var/lib/postgresql/data
    profiles:
      - database
      - fullstack
      - backend

  campaign-db:
    image: postgres:14
    container_name: campaign_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB__CAMPAIGN}
    ports:
      - "55434:5432"
    volumes:
      - campaign_db_data:/var/lib/postgresql/data
    profiles:
      - database
      - fullstack
      - backend

  # Frontends
  world-building-ui:
    build:
      context: ./frontend/world-building-ui
      dockerfile: Dockerfile.dev
    container_name: world_building_ui
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/world-building-ui:/usr/src/app
    depends_on:
      - frontend-proto-generator
      - content-service
      - envoy
    profiles:
      - frontend
      - fullstack

  # Proto Generation Service for Frontend
  frontend-proto-generator:
    image: node:18
    container_name: frontend_proto_generator
    working_dir: /usr/src/app
    volumes:
      - ./frontend/world-building-ui:/usr/src/app
    command: sh -c "npm install && npm run proto:generate"
    profiles:
      - frontend
      - fullstack
    # Ensure this service runs before the UI service
    depends_on:
      - world-db
      - campaign-db

volumes:
  world_db_data:
  campaign_db_data:
