export enum TraitTypeEnum {
    TRAIT_CONGENITAL = "CONGENITAL",
    TRAIT_COPING = "COPING",
    TRAIT_EDUCATION = "EDUCATION",
    TRAIT_FAITH = "FAITH",
    TRAIT_HEALTH = "HEALTH",
    TRAIT_INFAMY = "INFAMY",
    TRAIT_LEVELED = "LEVELED",
    TRAIT_LIFESTYLE = "LIFESTYLE",
    TRAIT_PERSONALITY = "PERSONALITY",
    TRAIT_PHYSICAL = "PHYSICAL",
}