import { DICE_OUTCOME_ENUM } from "../enum/DICE_OUTCOME_ENUM";
import { SCALE_TYPE_ENUM } from "../enum/SCALE_TYPE_ENUM";
import { DiceScaleConfig, DiceScaleConfigItem } from "../types";

const D20_LOW_RISK_LOW_IMPACT_SCALE: DiceScaleConfigItem = {
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_FAILURE]: "1",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_FAILURE]: null,
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_FAILURE]: "2-3",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_NEUTRAL_OUTCOME]: "4-17",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_SUCCESS]: "18-19",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_SUCCESS]: null,
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_SUCCESS]: "20"
};

const D20_MEDIUM_RISK_LOW_IMPACT_SCALE: DiceScaleConfigItem = {
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_FAILURE]: "1",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_FAILURE]: "2",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_FAILURE]: "3-5",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_NEUTRAL_OUTCOME]: "6-15",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_SUCCESS]: "16-18",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_SUCCESS]: "19",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_SUCCESS]: "20"
};

const D20_HIGH_RISK_LOW_IMPACT_SCALE: DiceScaleConfigItem = {
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_FAILURE]: "1-3",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_FAILURE]: "4-6",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_FAILURE]: "7-10",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_NEUTRAL_OUTCOME]: "11-13",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_SUCCESS]: "14-17",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_SUCCESS]: "18-19",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_SUCCESS]: "20"
};



const D20_LOW_RISK_MEDIUM_IMPACT_SCALE: DiceScaleConfigItem = {
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_FAILURE]: "1",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_FAILURE]: "2-3",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_FAILURE]: "4-6",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_NEUTRAL_OUTCOME]: "7-15",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_SUCCESS]: "16-18",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_SUCCESS]: "19",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_SUCCESS]: "20"
};

const D20_MEDIUM_RISK_MEDIUM_IMPACT_SCALE: DiceScaleConfigItem = {
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_FAILURE]: "1-3",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_FAILURE]: "4-6",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_FAILURE]: "7-10",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_NEUTRAL_OUTCOME]: "11-13",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_SUCCESS]: "14-16",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_SUCCESS]: "17-19",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_SUCCESS]: "20"
};

const D20_HIGH_RISK_MEDIUM_IMPACT_SCALE: DiceScaleConfigItem = {
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_FAILURE]: "1-5",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_FAILURE]: "6-8",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_FAILURE]: "9-12",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_NEUTRAL_OUTCOME]: "13-14",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_SUCCESS]: "15-17",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_SUCCESS]: "18-19",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_SUCCESS]: "20"
};



const D20_LOW_RISK_HIGH_IMPACT_SCALE: DiceScaleConfigItem = {
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_FAILURE]: "1",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_FAILURE]: "2-3",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_FAILURE]: "4-6",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_NEUTRAL_OUTCOME]: "7-14",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_SUCCESS]: "15-18",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_SUCCESS]: "19",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_SUCCESS]: "20"
};

const D20_MEDIUM_RISK_HIGH_IMPACT_SCALE: DiceScaleConfigItem = {
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_FAILURE]: "1-3",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_FAILURE]: "4-6",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_FAILURE]: "7-10",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_NEUTRAL_OUTCOME]: "11-12",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_SUCCESS]: "13-16",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_SUCCESS]: "17-19",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_SUCCESS]: "20"
};

const D20_HIGH_RISK_HIGH_IMPACT_SCALE: DiceScaleConfigItem = {
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_FAILURE]: "1-5",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_FAILURE]: "6-8",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_FAILURE]: "9-12",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_NEUTRAL_OUTCOME]: "13-14",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_MILD_SUCCESS]: "15-17",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_STRONG_SUCCESS]: "18-19",
    [DICE_OUTCOME_ENUM.DICE_OUTCOME_CRITICAL_SUCCESS]: "20"
};


export const D20_SCALE_CONFIG: DiceScaleConfig = {
    sides: 20,
    items: {
        [SCALE_TYPE_ENUM.LOW_RISK_LOW_IMPACT]: D20_LOW_RISK_LOW_IMPACT_SCALE,
        [SCALE_TYPE_ENUM.LOW_RISK_MEDIUM_IMPACT]: D20_LOW_RISK_MEDIUM_IMPACT_SCALE,
        [SCALE_TYPE_ENUM.LOW_RISK_HIGH_IMPACT]: D20_LOW_RISK_HIGH_IMPACT_SCALE,
        [SCALE_TYPE_ENUM.MEDIUM_RISK_LOW_IMPACT]: D20_MEDIUM_RISK_LOW_IMPACT_SCALE,
        [SCALE_TYPE_ENUM.MEDIUM_RISK_MEDIUM_IMPACT]: D20_MEDIUM_RISK_MEDIUM_IMPACT_SCALE,
        [SCALE_TYPE_ENUM.MEDIUM_RISK_HIGH_IMPACT]: D20_MEDIUM_RISK_HIGH_IMPACT_SCALE,
        [SCALE_TYPE_ENUM.HIGH_RISK_LOW_IMPACT]: D20_HIGH_RISK_LOW_IMPACT_SCALE,
        [SCALE_TYPE_ENUM.HIGH_RISK_MEDIUM_IMPACT]: D20_HIGH_RISK_MEDIUM_IMPACT_SCALE,
        [SCALE_TYPE_ENUM.HIGH_RISK_HIGH_IMPACT]: D20_HIGH_RISK_HIGH_IMPACT_SCALE
    }
}