import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateCampaignSchema1735147290713 implements MigrationInterface {
    name = 'CreateCampaignSchema1735147290713'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "equipment_slot" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(64) NOT NULL, "allowedEntities" jsonb NOT NULL, "equippedItemId" character varying, "characterId" character varying, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "REL_45a7d1e4c102ae58619b2e28b3" UNIQUE ("equippedItemId"), CONSTRAINT "PK_44eb99c530eaa150ee8730a65f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "storage_slot" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(50) NOT NULL, "grid" jsonb, "gridState" jsonb NOT NULL DEFAULT '[]', "maxWeight" integer, "parentItemId" character varying, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_805217ed1be01b4e17d0bfc8f49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL DEFAULT 'PLACEHOLDER', "description" character varying, "size" jsonb, "weight" double precision NOT NULL DEFAULT '0', "quantity" integer NOT NULL DEFAULT '1', "maxQuantity" integer NOT NULL DEFAULT '64', "baseValue" integer NOT NULL DEFAULT '0', "trainedSkill" character varying, "actions" jsonb, "requirements" jsonb, "consumable" boolean NOT NULL DEFAULT false, "stackable" boolean NOT NULL DEFAULT false, "repairable" boolean NOT NULL DEFAULT false, "drinkable" boolean NOT NULL DEFAULT false, "edible" boolean NOT NULL DEFAULT false, "gridPosition" jsonb, "storageSlotDefinition" jsonb, "durability" integer DEFAULT '0', "maxDurability" integer DEFAULT '0', "damagePierce" character varying, "armorClass" integer, "stealthDisadvantage" boolean, "damageSlash" character varying, "damageBlunt" character varying, "range" character varying, "twoHanded" boolean DEFAULT false, "nutrition" integer DEFAULT '0', "spoilage" integer DEFAULT '0', "thirstQuenched" integer DEFAULT '0', "type" character varying NOT NULL, "storageSlotId" character varying, "equipmentSlotId" character varying, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_d3c0c71f23e7adcf952a1d13423" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a6c7fa282dcacbfe6247b28f13" ON "item" ("type") `);
        await queryRunner.query(`CREATE TYPE "public"."past_experience_exptype_enum" AS ENUM('CHILD', 'ADULT')`);
        await queryRunner.query(`CREATE TABLE "past_experience" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL, "expType" "public"."past_experience_exptype_enum" NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_b54bcc163c63c43be997854031d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "memory_pool_entry" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL, "probability" double precision NOT NULL DEFAULT '1', "defaultClarity" integer NOT NULL DEFAULT '1', "defaultImportance" integer NOT NULL DEFAULT '1', "memoryPoolId" character varying, "memoryId" character varying, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_f97752de9ca6a28930025cf89c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "character_profession" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(60) NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_641c1ba8d7808f4bd1fed365843" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "memory_pool" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL DEFAULT 'PLACEHOLDER', "description" text, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_a1ae06af62fb9c046440e2c25cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."skill_category_enum" AS ENUM('CRAFTING', 'MAGIC', 'COMBAT', 'STEALTH', 'SOCIAL')`);
        await queryRunner.query(`CREATE TABLE "skill" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(50) NOT NULL, "description" character varying(255) NOT NULL, "category" "public"."skill_category_enum" NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_a0d33334424e64fb78dc3ce7196" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."trait_traittype_enum" AS ENUM('CONGENITAL', 'COPING', 'EDUCATION', 'FAITH', 'HEALTH', 'INFAMY', 'LEVELED', 'LIFESTYLE', 'PERSONALITY', 'PHYSICAL')`);
        await queryRunner.query(`CREATE TABLE "trait" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL DEFAULT 'PLACEHOLDER', "traitType" "public"."trait_traittype_enum" NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_c5d145e577199fe58afbf2a1b2d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."disease_severity_enum" AS ENUM('MILD', 'MODERATE', 'SEVERE')`);
        await queryRunner.query(`CREATE TABLE "disease" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "severity" "public"."disease_severity_enum" NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_f7a8573a47cdc044735eda4644b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."effect_type_enum" AS ENUM('DAMAGE', 'HEALING', 'BUFF', 'DEBUFF', 'RESISTANCE', 'STEALING', 'NEUTRAL', 'UNRECOGNIZED')`);
        await queryRunner.query(`CREATE TYPE "public"."effect_target_enum" AS ENUM('HEALTH', 'STAMINA', 'MANA')`);
        await queryRunner.query(`CREATE TYPE "public"."effect_mode_enum" AS ENUM('INSTANT', 'GRADUAL', 'PERSISTENT')`);
        await queryRunner.query(`CREATE TYPE "public"."effect_element_enum" AS ENUM('FIRE', 'FROST', 'POISON', 'SHOCK')`);
        await queryRunner.query(`CREATE TABLE "effect" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL DEFAULT 'PLACEHOLDER', "type" "public"."effect_type_enum" NOT NULL, "target" "public"."effect_target_enum" NOT NULL, "mode" "public"."effect_mode_enum" NOT NULL, "element" "public"."effect_element_enum", "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_d9f2bcb19b53f7f26e0b7c484e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "faction" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_5935637aa4ecd999ac0555ae5a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tag_subtype_enum" AS ENUM('MATERIAL', 'CULTURE', 'RELATION', 'FACTION', 'RELIGION', 'WEAPON_QUALITY', 'ARMOR_QUALITY', 'WEAPON_TYPE', 'STATUS', 'QUEST')`);
        await queryRunner.query(`CREATE TABLE "tag" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "label" character varying(30) NOT NULL, "subtype" "public"."tag_subtype_enum" NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "UQ_647c189a51deb35bc452751bc4a" UNIQUE ("label"), CONSTRAINT "PK_8e4052373c579afc1471f526760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fact" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "weight" integer NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_99f436f7582af519be409af9f9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."memory_type_enum" AS ENUM('GLOBAL', 'REGIONAL', 'EVENT_RELATED', 'HISTORIC', 'PERSONAL')`);
        await queryRunner.query(`CREATE TABLE "memory" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "type" "public"."memory_type_enum" NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_719a982d08209b92cd1a0b1c4ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "character_memory" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL, "factStatus" jsonb, "importance" integer NOT NULL DEFAULT '1', "resistance" integer NOT NULL DEFAULT '0', "accumulator" integer NOT NULL DEFAULT '0', "acquiredAt" TIMESTAMP NOT NULL DEFAULT now(), "lastUpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "characterId" character varying, "memoryId" character varying, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_767851facbbb2f5b2562cee9822" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d1cf68b70d1f49512d8dda791d" ON "character_memory" ("type") `);
        await queryRunner.query(`CREATE TABLE "birthsign" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(50) NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_b2551602613d86398c561dd3049" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "race" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(255) NOT NULL, "equipment_slot_definitions" jsonb NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_a3068b184130d87a20e516045bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."character_gender_enum" AS ENUM('MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TABLE "character" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "firstName" character varying(255) NOT NULL, "lastName" character varying(255) NOT NULL, "gender" "public"."character_gender_enum" NOT NULL, "birthEra" character varying, "birthYear" integer, "birthMonth" character varying, "birthDay" integer, "skills" jsonb NOT NULL DEFAULT '{}', "enneagramType" character varying(3) NOT NULL, "raceId" character varying, "birthsignId" character varying, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_6c4aec48c564968be15078b8ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "addiction" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_61baf19579e81ef3a741907961e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "background" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(255) NOT NULL, "gender" jsonb, "faction" jsonb, "disease" jsonb, "addiction" jsonb, "profession" jsonb, "race" jsonb, "religion" jsonb, "personality" jsonb, "items" jsonb, "itemSets" jsonb, "pastExpChild" jsonb, "pastExpAdult" jsonb, "memoryPools" jsonb, "skillSets" jsonb, "skillAdjustments" jsonb, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_7271b4d2e4bd0f68b3fdb5c090a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item_set" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "set" jsonb NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_1128d71c6ec0efaa6fbba46d36d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mood" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_cd069bf46deedf0ef3a7771f44b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."need_type_enum" AS ENUM('DYNAMIC', 'THRESHOLD', 'EXTERNAL')`);
        await queryRunner.query(`CREATE TYPE "public"."need_layer_enum" AS ENUM('PHYSIOLOGICAL', 'SAFETY', 'BELONGING_AND_LOVE', 'ESTEEM', 'COGNITIVE', 'AESTHETIC', 'SELF_ACTUALIZATION', 'TRANSCENDENCE')`);
        await queryRunner.query(`CREATE TABLE "need" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "type" "public"."need_type_enum" NOT NULL, "layer" "public"."need_layer_enum" NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_218b14514f334ee6f39954f86ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "personality_profile" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(255) NOT NULL, "enneagramType" character varying(3) NOT NULL, "traits" jsonb NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_7dfad550a40c2a38d8be300a61c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "religion" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "rituals" jsonb, "tenets" jsonb, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_fcfc9cd803b178c11fd21285d30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."resistance_effecttype_enum" AS ENUM('DAMAGE', 'HEALING', 'BUFF', 'DEBUFF', 'RESISTANCE', 'STEALING', 'NEUTRAL', 'UNRECOGNIZED')`);
        await queryRunner.query(`CREATE TABLE "resistance" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(255) NOT NULL, "effectType" "public"."resistance_effecttype_enum" NOT NULL, "targetEffect" character varying, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_8b91aa1a4b047294b638b3c9f3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."status_type_enum" AS ENUM('DAMAGE', 'HEALING', 'BUFF', 'DEBUFF', 'RESISTANCE', 'STEALING', 'NEUTRAL', 'UNRECOGNIZED')`);
        await queryRunner.query(`CREATE TABLE "status" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "type" "public"."status_type_enum" NOT NULL, "effects" text, "duration" integer, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_e12743a7086ec826733f54e1d95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_record" ("id" character varying NOT NULL, "eventName" character varying(255) NOT NULL, "label" character varying(255) NOT NULL, "relatedTargetEntity" character varying(255), "relatedTargetId" character varying(255), "relatedEntityName" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "worldId" character varying, "userId" character varying, "campaignId" character varying, CONSTRAINT "PK_a7314c500ea63e9981c91dc03a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "world" ("id" character varying NOT NULL, "name" character varying(255) NOT NULL, "description" text, "settings" json, "frozen" boolean NOT NULL DEFAULT false, "type" character varying NOT NULL, "userId" character varying, CONSTRAINT "PK_9a0e469d5311d0d95ce1202c990" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1cbb465c75a18296ce364ffdc8" ON "world" ("type") `);
        await queryRunner.query(`CREATE TABLE "campaign" ("id" character varying NOT NULL, "name" character varying(255) NOT NULL, "description" text, "dynamicState" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "worldId" character varying, "userId" character varying, CONSTRAINT "PK_0ce34d26e7f2eb316a3a592cdc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4f0678ebd019c0ffcc5f60c78c" ON "campaign" ("type") `);
        await queryRunner.query(`CREATE TYPE "public"."account_role_enum" AS ENUM('player', 'admin')`);
        await queryRunner.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "username" character varying NOT NULL, "passwordHash" character varying(255) NOT NULL, "email" character varying(255), "role" "public"."account_role_enum", "preferences" json, "type" character varying NOT NULL, "userId" character varying, CONSTRAINT "UQ_41dfcb70af895ddf9a53094515b" UNIQUE ("username"), CONSTRAINT "REL_60328bf27019ff5498c4b97742" UNIQUE ("userId"), CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3c76f178c5065d1ab304b5832e" ON "account" ("type") `);
        await queryRunner.query(`CREATE TABLE "user" ("id" character varying NOT NULL, "type" character varying NOT NULL, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_31ef2b4d30675d0c15056b7f6e" ON "user" ("type") `);
        await queryRunner.query(`CREATE TYPE "public"."character_gen_instruction_gender_enum" AS ENUM('MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TABLE "character_gen_instruction" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "firstName" character varying, "lastName" character varying, "gender" "public"."character_gen_instruction_gender_enum", "birthsign" character varying, "birthEra" character varying, "birthYear" integer, "birthMonth" character varying, "birthDay" integer, "backgroundBlueprintId" character varying NOT NULL, "backgroundCustomization" jsonb, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_77db152a9b12a648ef158f3376d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "character_group_gen_instruction" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying NOT NULL, "set" jsonb NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_65e9920b8fc2d42ba1e6927e493" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "skill_set" ("blueprintId" character varying(255), "metadata" json, "targetEntity" character varying NOT NULL, "id" character varying NOT NULL, "name" character varying(64) NOT NULL, "skillImprovement" jsonb NOT NULL, "userId" character varying, "campaignId" character varying, "worldId" character varying, CONSTRAINT "PK_d94825f899a97846bca90d9952e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "character_profession_characters_character" ("characterProfessionId" character varying NOT NULL, "characterId" character varying NOT NULL, CONSTRAINT "PK_6d653c47c3d9ccff9a1d766b7db" PRIMARY KEY ("characterProfessionId", "characterId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8a5ceae9e532cbb0ce61f17007" ON "character_profession_characters_character" ("characterProfessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7ce4bf82a5166b7ba3d167aca" ON "character_profession_characters_character" ("characterId") `);
        await queryRunner.query(`CREATE TABLE "character_profession_memory_pools_memory_pool" ("characterProfessionId" character varying NOT NULL, "memoryPoolId" character varying NOT NULL, CONSTRAINT "PK_33f7d2fe2bd6a9d12db00a5abb8" PRIMARY KEY ("characterProfessionId", "memoryPoolId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c663023d36c63c9940a21d8e2d" ON "character_profession_memory_pools_memory_pool" ("characterProfessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6ec9345cfc82ffbd567c5ee8a" ON "character_profession_memory_pools_memory_pool" ("memoryPoolId") `);
        await queryRunner.query(`CREATE TABLE "tag_items_item" ("tagId" character varying NOT NULL, "itemId" character varying NOT NULL, CONSTRAINT "PK_6260cb39bf50bf0e1fafb3b9fcf" PRIMARY KEY ("tagId", "itemId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6556352a2772efbe24fc2647bb" ON "tag_items_item" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e9c60c0a746da155dfe0c3a82" ON "tag_items_item" ("itemId") `);
        await queryRunner.query(`CREATE TABLE "tag_past_experiences_past_experience" ("tagId" character varying NOT NULL, "pastExperienceId" character varying NOT NULL, CONSTRAINT "PK_1f9ad7e1b2efdab127db7178a2f" PRIMARY KEY ("tagId", "pastExperienceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1dc46da1182ac79facb9ca9e58" ON "tag_past_experiences_past_experience" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8016f291bf0c652f47871ff16" ON "tag_past_experiences_past_experience" ("pastExperienceId") `);
        await queryRunner.query(`CREATE TABLE "tag_character_memories_character_memory" ("tagId" character varying NOT NULL, "characterMemoryId" character varying NOT NULL, CONSTRAINT "PK_f180c77ecfe8e7f2f8ff90c1bb4" PRIMARY KEY ("tagId", "characterMemoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b07d9250d6748cd3d32bb59ff7" ON "tag_character_memories_character_memory" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_25f234875a96669139ff28aa54" ON "tag_character_memories_character_memory" ("characterMemoryId") `);
        await queryRunner.query(`CREATE TABLE "tag_memories_memory" ("tagId" character varying NOT NULL, "memoryId" character varying NOT NULL, CONSTRAINT "PK_9959d5a125d0b0884cb54d89509" PRIMARY KEY ("tagId", "memoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90235abd5e059aabbeca65c4f2" ON "tag_memories_memory" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c928dd23aa5b7d71aa3136a6b" ON "tag_memories_memory" ("memoryId") `);
        await queryRunner.query(`CREATE TABLE "tag_memory_pools_memory_pool" ("tagId" character varying NOT NULL, "memoryPoolId" character varying NOT NULL, CONSTRAINT "PK_7ef25950691db219b1b85722277" PRIMARY KEY ("tagId", "memoryPoolId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e1cbcaa49961df1ba43c725dc1" ON "tag_memory_pools_memory_pool" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f27f02099bf1cff4297e544c87" ON "tag_memory_pools_memory_pool" ("memoryPoolId") `);
        await queryRunner.query(`CREATE TABLE "tag_skills_skill" ("tagId" character varying NOT NULL, "skillId" character varying NOT NULL, CONSTRAINT "PK_0199f3917fb3571a7496eb892b9" PRIMARY KEY ("tagId", "skillId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bbc0567f3d42c0d4da19f6120e" ON "tag_skills_skill" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d46f32fb9e84e13d4754599394" ON "tag_skills_skill" ("skillId") `);
        await queryRunner.query(`CREATE TABLE "tag_traits_trait" ("tagId" character varying NOT NULL, "traitId" character varying NOT NULL, CONSTRAINT "PK_110ec2e91cd5e717a1640488d05" PRIMARY KEY ("tagId", "traitId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b1f9131098d4567bb35be25d6" ON "tag_traits_trait" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3099a9a34ecc1e80b056ff967" ON "tag_traits_trait" ("traitId") `);
        await queryRunner.query(`CREATE TABLE "tag_characters_character" ("tagId" character varying NOT NULL, "characterId" character varying NOT NULL, CONSTRAINT "PK_f3b1918387f5a44cdd64156f652" PRIMARY KEY ("tagId", "characterId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba07cd68937697325925e117d1" ON "tag_characters_character" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_27cabd722238a3ad436d21f5ec" ON "tag_characters_character" ("characterId") `);
        await queryRunner.query(`CREATE TABLE "tag_character_professions_character_profession" ("tagId" character varying NOT NULL, "characterProfessionId" character varying NOT NULL, CONSTRAINT "PK_e3766bda41cd10b343c8b53d1bc" PRIMARY KEY ("tagId", "characterProfessionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4f942fcd8475de7d439483e10" ON "tag_character_professions_character_profession" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d23da5f829aa85fb29cdae5e78" ON "tag_character_professions_character_profession" ("characterProfessionId") `);
        await queryRunner.query(`CREATE TABLE "tag_diseases_disease" ("tagId" character varying NOT NULL, "diseaseId" character varying NOT NULL, CONSTRAINT "PK_e69d8854023857067bfa7382433" PRIMARY KEY ("tagId", "diseaseId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b65ac2bf7270d60ead58e5948c" ON "tag_diseases_disease" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_968cc66f706cd6c80bc0b9af44" ON "tag_diseases_disease" ("diseaseId") `);
        await queryRunner.query(`CREATE TABLE "tag_effects_effect" ("tagId" character varying NOT NULL, "effectId" character varying NOT NULL, CONSTRAINT "PK_cfee670d5c30c05d6b568a99790" PRIMARY KEY ("tagId", "effectId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90f7534a5d05ee34893c6f008d" ON "tag_effects_effect" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_34f5cb09a55913c6f583bda3ad" ON "tag_effects_effect" ("effectId") `);
        await queryRunner.query(`CREATE TABLE "tag_facts_fact" ("tagId" character varying NOT NULL, "factId" character varying NOT NULL, CONSTRAINT "PK_dc8f56b4f2454ea5718d5e17261" PRIMARY KEY ("tagId", "factId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9b3bc792d5168ac5960d3be6c" ON "tag_facts_fact" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e59f64dd525be94f32cee86b4f" ON "tag_facts_fact" ("factId") `);
        await queryRunner.query(`CREATE TABLE "tag_factions_faction" ("tagId" character varying NOT NULL, "factionId" character varying NOT NULL, CONSTRAINT "PK_a4b746e3f448e7ee2b33f1d993c" PRIMARY KEY ("tagId", "factionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e59c738f7a540c58078321d316" ON "tag_factions_faction" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a2f5d9c7e82f8b9456dff3295" ON "tag_factions_faction" ("factionId") `);
        await queryRunner.query(`CREATE TABLE "memory_facts_fact" ("memoryId" character varying NOT NULL, "factId" character varying NOT NULL, CONSTRAINT "PK_595a8ba22261246eab8c18b04a5" PRIMARY KEY ("memoryId", "factId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8db0b9d2a2cd357ec77909ceee" ON "memory_facts_fact" ("memoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c3179e191a3edde7594940ae1" ON "memory_facts_fact" ("factId") `);
        await queryRunner.query(`CREATE TABLE "character_memory_pools_memory_pool" ("characterId" character varying NOT NULL, "memoryPoolId" character varying NOT NULL, CONSTRAINT "PK_ae6ae92ba3650c76e24b617f583" PRIMARY KEY ("characterId", "memoryPoolId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a249962a51899b420b63ce13ae" ON "character_memory_pools_memory_pool" ("characterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_90b4030407893812c08d19155d" ON "character_memory_pools_memory_pool" ("memoryPoolId") `);
        await queryRunner.query(`CREATE TABLE "character_traits_trait" ("characterId" character varying NOT NULL, "traitId" character varying NOT NULL, CONSTRAINT "PK_2f7c5f5119083526d63e943d0ac" PRIMARY KEY ("characterId", "traitId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f94b5bf13399bf9da978917f9b" ON "character_traits_trait" ("characterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4587390389294a489dd2986bf7" ON "character_traits_trait" ("traitId") `);
        await queryRunner.query(`CREATE TABLE "character_diseases_disease" ("characterId" character varying NOT NULL, "diseaseId" character varying NOT NULL, CONSTRAINT "PK_790d5a40126139dce5aeed5f3f7" PRIMARY KEY ("characterId", "diseaseId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f44b728362ad3acdb4434a71e4" ON "character_diseases_disease" ("characterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_418a8fb4eeaefcf9c762f1cdae" ON "character_diseases_disease" ("diseaseId") `);
        await queryRunner.query(`CREATE TABLE "character_addictions_addiction" ("characterId" character varying NOT NULL, "addictionId" character varying NOT NULL, CONSTRAINT "PK_6e8a51fa0e852bde6642a822a3a" PRIMARY KEY ("characterId", "addictionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf12cdf7300952d29ab46852c7" ON "character_addictions_addiction" ("characterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_588a0e8246203d8579a0de3d18" ON "character_addictions_addiction" ("addictionId") `);
        await queryRunner.query(`CREATE TABLE "character_past_experiences_past_experience" ("characterId" character varying NOT NULL, "pastExperienceId" character varying NOT NULL, CONSTRAINT "PK_e3c396c24104fc75618eaf0b9f2" PRIMARY KEY ("characterId", "pastExperienceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72286a7702cf4f22ba08c8837e" ON "character_past_experiences_past_experience" ("characterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_746f5b48b27e8874231ce9e7d6" ON "character_past_experiences_past_experience" ("pastExperienceId") `);
        await queryRunner.query(`CREATE TABLE "character_factions_faction" ("characterId" character varying NOT NULL, "factionId" character varying NOT NULL, CONSTRAINT "PK_91a636bb98737d35db13dad0bf4" PRIMARY KEY ("characterId", "factionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_04c0fd053667adbdc11e842356" ON "character_factions_faction" ("characterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13d11465ba7c90a36ddc957f65" ON "character_factions_faction" ("factionId") `);
        await queryRunner.query(`CREATE TABLE "character_tags_tag" ("characterId" character varying NOT NULL, "tagId" character varying NOT NULL, CONSTRAINT "PK_bf5692b2c3a1661ac37315600da" PRIMARY KEY ("characterId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd444fc59bf0f731494ab1fe1d" ON "character_tags_tag" ("characterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f767c44fc839f4d53aedb2bd9f" ON "character_tags_tag" ("tagId") `);
        await queryRunner.query(`ALTER TABLE "equipment_slot" ADD CONSTRAINT "FK_45a7d1e4c102ae58619b2e28b31" FOREIGN KEY ("equippedItemId") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment_slot" ADD CONSTRAINT "FK_9b36abbed55a1ba5a0d3e7ead50" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment_slot" ADD CONSTRAINT "FK_669bbb6ed0d463595798c2f0b39" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment_slot" ADD CONSTRAINT "FK_70883e6df724e96155c15b6af19" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment_slot" ADD CONSTRAINT "FK_9ffd83dbfdeedcaf88135efbb2a" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "storage_slot" ADD CONSTRAINT "FK_1eb0325057d973a9c0e9531f20b" FOREIGN KEY ("parentItemId") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "storage_slot" ADD CONSTRAINT "FK_3a645eb3e5dffeb6fc1efd532ff" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "storage_slot" ADD CONSTRAINT "FK_1b84d3566518cef431e04feaaee" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "storage_slot" ADD CONSTRAINT "FK_0a24a514d42d95dd51640165de8" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item" ADD CONSTRAINT "FK_fc4c2662a5b62d957af5a9793c5" FOREIGN KEY ("storageSlotId") REFERENCES "storage_slot"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item" ADD CONSTRAINT "FK_3312c0e101d61169d3fdc075e11" FOREIGN KEY ("equipmentSlotId") REFERENCES "equipment_slot"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item" ADD CONSTRAINT "FK_5369db3bd33839fd3b0dd5525d1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item" ADD CONSTRAINT "FK_59ea1273219627c436037622fd7" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item" ADD CONSTRAINT "FK_d4cce4776d3c0aa3ae2cea52d09" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "past_experience" ADD CONSTRAINT "FK_59d514d09b646b4aa3f2185d4e8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "past_experience" ADD CONSTRAINT "FK_7073aac60002dbfdb42e0451973" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "past_experience" ADD CONSTRAINT "FK_403d570c9847f7e303e3c908463" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_pool_entry" ADD CONSTRAINT "FK_95ac39a7c5f9fab41fa9bd724ac" FOREIGN KEY ("memoryPoolId") REFERENCES "memory_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_pool_entry" ADD CONSTRAINT "FK_5db0f5a08b1bc82b85b43f06570" FOREIGN KEY ("memoryId") REFERENCES "memory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_pool_entry" ADD CONSTRAINT "FK_10613f49638aa623782d979013d" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_pool_entry" ADD CONSTRAINT "FK_4a41d71a6dbadcb813692a520c6" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_pool_entry" ADD CONSTRAINT "FK_47ac54fff26122aa2f8a1648549" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_profession" ADD CONSTRAINT "FK_56858e2c85bf45a6fa7fb699d2e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_profession" ADD CONSTRAINT "FK_66ed53e4c3526a9fd87374b4314" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_profession" ADD CONSTRAINT "FK_a24df76b4923bae1762434f3ae9" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_pool" ADD CONSTRAINT "FK_1c9398af617de82b702fa43291e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_pool" ADD CONSTRAINT "FK_42665701f2d9ad130c0b334182f" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_pool" ADD CONSTRAINT "FK_a19c20c44be4479989c208d33ba" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill" ADD CONSTRAINT "FK_c08612011a88745a32784544b28" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill" ADD CONSTRAINT "FK_e052e54357fbe0afca4605460b3" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill" ADD CONSTRAINT "FK_7625c2a421455904cb1fd4484c0" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trait" ADD CONSTRAINT "FK_98b5a61037704fbae5012accc9f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trait" ADD CONSTRAINT "FK_2081978dfdc2941d78b00a339f3" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trait" ADD CONSTRAINT "FK_dcccbe68509ea2fdf0596d15f8c" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disease" ADD CONSTRAINT "FK_d8fd3cb70b5e1ae39415bf97473" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disease" ADD CONSTRAINT "FK_9e2723c06088ac577a831b7204b" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disease" ADD CONSTRAINT "FK_cab8d6d8c256f68719a540aff5e" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "effect" ADD CONSTRAINT "FK_92fe6934186fd55be63731ebd4c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "effect" ADD CONSTRAINT "FK_eacae13387b50f668e1614c7734" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "effect" ADD CONSTRAINT "FK_b09feadeed78b169d74a2194080" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faction" ADD CONSTRAINT "FK_4a708eed0751a8034015b18a607" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faction" ADD CONSTRAINT "FK_8d852638fb4e8c8adbea8410f8b" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faction" ADD CONSTRAINT "FK_1371bd66122552183eb1dd71672" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag" ADD CONSTRAINT "FK_d0dc39ff83e384b4a097f47d3f5" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag" ADD CONSTRAINT "FK_7e786468c032bf87daca95994f1" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag" ADD CONSTRAINT "FK_0c871deb494195392af68036e5a" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fact" ADD CONSTRAINT "FK_6b6ea6cb2b2ac96f3c62cc63fab" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fact" ADD CONSTRAINT "FK_d0b06f4dfeec255770cf9976745" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fact" ADD CONSTRAINT "FK_2d5fb22888c1e80aa08411bc922" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory" ADD CONSTRAINT "FK_fc71562e9a53841973da0dde326" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory" ADD CONSTRAINT "FK_53a0f60ba10a56672e87dbaecb1" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory" ADD CONSTRAINT "FK_4abb0599b000b0ce3dec5b17a53" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_memory" ADD CONSTRAINT "FK_f13b49c601ff82b31ffc6e7f4fa" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_memory" ADD CONSTRAINT "FK_e542b99701d4afa005afe285a82" FOREIGN KEY ("memoryId") REFERENCES "memory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_memory" ADD CONSTRAINT "FK_03bc5aa08e9b1ffbf4fcc4bfd75" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_memory" ADD CONSTRAINT "FK_c2e1e6b2326c881926cce63883b" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_memory" ADD CONSTRAINT "FK_41d2915bf350b5c29b1995d0330" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "birthsign" ADD CONSTRAINT "FK_2d767e0eba389143a97ace754c9" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "birthsign" ADD CONSTRAINT "FK_2854aee8c563fb181a507e5631a" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "birthsign" ADD CONSTRAINT "FK_b1199ea47fb769d1798555d35de" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "race" ADD CONSTRAINT "FK_c8a61aead3a0e005451152cb537" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "race" ADD CONSTRAINT "FK_cf53c6c61bb2ee5c5cdc874e16f" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "race" ADD CONSTRAINT "FK_3838011cae1fc347a263518fdaf" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_a7485d062b19695002b6175e8fb" FOREIGN KEY ("raceId") REFERENCES "race"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_f18d5273f1ae641d654b8e11367" FOREIGN KEY ("birthsignId") REFERENCES "birthsign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_04c2fb52adfa5265763de8c4464" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_e65d0f0d18bac2d48aa3075ca7c" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_73e8e485b0af5b70e156bdbf2d5" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addiction" ADD CONSTRAINT "FK_9c8cb34be63636f5df1c513fc90" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addiction" ADD CONSTRAINT "FK_b12bba127811e59ba1d457134d5" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addiction" ADD CONSTRAINT "FK_72c3e468018000fec2fb7de15a8" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "background" ADD CONSTRAINT "FK_0b97b6d92d5cceb85ce6059e49a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "background" ADD CONSTRAINT "FK_3ca60c28267a0e7416b2ca11853" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "background" ADD CONSTRAINT "FK_514595bb7be1200882f61a58e71" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_set" ADD CONSTRAINT "FK_b1c759d6706ebfc007af98ad4b3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_set" ADD CONSTRAINT "FK_2af689c42c21ec52fecf498edb1" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_set" ADD CONSTRAINT "FK_ea55fc163151757d1812bb142e6" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mood" ADD CONSTRAINT "FK_063b678cbb2c84dfd95dff5da22" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mood" ADD CONSTRAINT "FK_bdcb2ca72fc62cbbf070be1992a" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mood" ADD CONSTRAINT "FK_f963136b0294ba43499ffb3dc1d" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "need" ADD CONSTRAINT "FK_31b9dddb3ba04700bafa1ddc388" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "need" ADD CONSTRAINT "FK_fd881c0ba71e17dfb9eebdee61f" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "need" ADD CONSTRAINT "FK_4e9cef3d64e8ec4b4b9e8808001" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personality_profile" ADD CONSTRAINT "FK_d5cc9f84863e90798509a241acb" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personality_profile" ADD CONSTRAINT "FK_c31fd8278f85301590c66deab06" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personality_profile" ADD CONSTRAINT "FK_ad178fd7a19d09562d293af5f12" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "religion" ADD CONSTRAINT "FK_d9685bba5b8ec311605e6de213e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "religion" ADD CONSTRAINT "FK_1b805d14cbc9bf981aecb4e138c" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "religion" ADD CONSTRAINT "FK_7144ce1861ab742646361527756" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resistance" ADD CONSTRAINT "FK_16fb3bd7b74f585bb893a088209" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resistance" ADD CONSTRAINT "FK_a7ae9428eab076395476966b0ea" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resistance" ADD CONSTRAINT "FK_735d519d3cf8c8a5d4f49e693d6" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "status" ADD CONSTRAINT "FK_94cb5dda3cf592da917ec3a2746" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "status" ADD CONSTRAINT "FK_530cec77ca73dd3bc39b7d7b7f4" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "status" ADD CONSTRAINT "FK_fc6c49a4d23d0c792d52631f0bb" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_record" ADD CONSTRAINT "FK_f3a947145cd73990b46f36bd661" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_record" ADD CONSTRAINT "FK_0f8f194a669e3c8b05dc8f9554b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_record" ADD CONSTRAINT "FK_7154b9208949faaf59c9559e3e3" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "world" ADD CONSTRAINT "FK_5c6f20a4c309c357a2934164b5e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaign" ADD CONSTRAINT "FK_7607a0ed92ad0cc487086069a8f" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaign" ADD CONSTRAINT "FK_8e2dc400e55e237feba0869bc02" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_60328bf27019ff5498c4b977421" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_gen_instruction" ADD CONSTRAINT "FK_c5059610267d87105696173dace" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_gen_instruction" ADD CONSTRAINT "FK_fce68c3bb2d59205371302d37ea" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_gen_instruction" ADD CONSTRAINT "FK_49ebb0c49defe82560701a3be06" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_group_gen_instruction" ADD CONSTRAINT "FK_9087e620410a2b6886505e2dcc6" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_group_gen_instruction" ADD CONSTRAINT "FK_1f4237c77fbce77d93bd236c294" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_group_gen_instruction" ADD CONSTRAINT "FK_6d63ce23da5b9594f29bf9c1aa4" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill_set" ADD CONSTRAINT "FK_41da8f0493a6d068d595026d50e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill_set" ADD CONSTRAINT "FK_d0c8a9758fbae427159b634309e" FOREIGN KEY ("campaignId") REFERENCES "campaign"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill_set" ADD CONSTRAINT "FK_d0d3cd62e50ac2fcd644dd1550f" FOREIGN KEY ("worldId") REFERENCES "world"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_profession_characters_character" ADD CONSTRAINT "FK_8a5ceae9e532cbb0ce61f170073" FOREIGN KEY ("characterProfessionId") REFERENCES "character_profession"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_profession_characters_character" ADD CONSTRAINT "FK_a7ce4bf82a5166b7ba3d167acae" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_profession_memory_pools_memory_pool" ADD CONSTRAINT "FK_c663023d36c63c9940a21d8e2dc" FOREIGN KEY ("characterProfessionId") REFERENCES "character_profession"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_profession_memory_pools_memory_pool" ADD CONSTRAINT "FK_a6ec9345cfc82ffbd567c5ee8a6" FOREIGN KEY ("memoryPoolId") REFERENCES "memory_pool"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_items_item" ADD CONSTRAINT "FK_6556352a2772efbe24fc2647bb2" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_items_item" ADD CONSTRAINT "FK_8e9c60c0a746da155dfe0c3a822" FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_past_experiences_past_experience" ADD CONSTRAINT "FK_1dc46da1182ac79facb9ca9e585" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_past_experiences_past_experience" ADD CONSTRAINT "FK_a8016f291bf0c652f47871ff16c" FOREIGN KEY ("pastExperienceId") REFERENCES "past_experience"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_character_memories_character_memory" ADD CONSTRAINT "FK_b07d9250d6748cd3d32bb59ff7d" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_character_memories_character_memory" ADD CONSTRAINT "FK_25f234875a96669139ff28aa54a" FOREIGN KEY ("characterMemoryId") REFERENCES "character_memory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_memories_memory" ADD CONSTRAINT "FK_90235abd5e059aabbeca65c4f28" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_memories_memory" ADD CONSTRAINT "FK_3c928dd23aa5b7d71aa3136a6b0" FOREIGN KEY ("memoryId") REFERENCES "memory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_memory_pools_memory_pool" ADD CONSTRAINT "FK_e1cbcaa49961df1ba43c725dc1e" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_memory_pools_memory_pool" ADD CONSTRAINT "FK_f27f02099bf1cff4297e544c872" FOREIGN KEY ("memoryPoolId") REFERENCES "memory_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_skills_skill" ADD CONSTRAINT "FK_bbc0567f3d42c0d4da19f6120ef" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_skills_skill" ADD CONSTRAINT "FK_d46f32fb9e84e13d47545993945" FOREIGN KEY ("skillId") REFERENCES "skill"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_traits_trait" ADD CONSTRAINT "FK_8b1f9131098d4567bb35be25d63" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_traits_trait" ADD CONSTRAINT "FK_c3099a9a34ecc1e80b056ff9677" FOREIGN KEY ("traitId") REFERENCES "trait"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_characters_character" ADD CONSTRAINT "FK_ba07cd68937697325925e117d10" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_characters_character" ADD CONSTRAINT "FK_27cabd722238a3ad436d21f5ec8" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_character_professions_character_profession" ADD CONSTRAINT "FK_f4f942fcd8475de7d439483e106" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_character_professions_character_profession" ADD CONSTRAINT "FK_d23da5f829aa85fb29cdae5e78d" FOREIGN KEY ("characterProfessionId") REFERENCES "character_profession"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_diseases_disease" ADD CONSTRAINT "FK_b65ac2bf7270d60ead58e5948c1" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_diseases_disease" ADD CONSTRAINT "FK_968cc66f706cd6c80bc0b9af44f" FOREIGN KEY ("diseaseId") REFERENCES "disease"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_effects_effect" ADD CONSTRAINT "FK_90f7534a5d05ee34893c6f008db" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_effects_effect" ADD CONSTRAINT "FK_34f5cb09a55913c6f583bda3adc" FOREIGN KEY ("effectId") REFERENCES "effect"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_facts_fact" ADD CONSTRAINT "FK_f9b3bc792d5168ac5960d3be6ca" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_facts_fact" ADD CONSTRAINT "FK_e59f64dd525be94f32cee86b4f3" FOREIGN KEY ("factId") REFERENCES "fact"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag_factions_faction" ADD CONSTRAINT "FK_e59c738f7a540c58078321d3167" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tag_factions_faction" ADD CONSTRAINT "FK_4a2f5d9c7e82f8b9456dff32958" FOREIGN KEY ("factionId") REFERENCES "faction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memory_facts_fact" ADD CONSTRAINT "FK_8db0b9d2a2cd357ec77909ceee8" FOREIGN KEY ("memoryId") REFERENCES "memory"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "memory_facts_fact" ADD CONSTRAINT "FK_8c3179e191a3edde7594940ae1d" FOREIGN KEY ("factId") REFERENCES "fact"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_memory_pools_memory_pool" ADD CONSTRAINT "FK_a249962a51899b420b63ce13ae0" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_memory_pools_memory_pool" ADD CONSTRAINT "FK_90b4030407893812c08d19155d2" FOREIGN KEY ("memoryPoolId") REFERENCES "memory_pool"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_traits_trait" ADD CONSTRAINT "FK_f94b5bf13399bf9da978917f9bf" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_traits_trait" ADD CONSTRAINT "FK_4587390389294a489dd2986bf73" FOREIGN KEY ("traitId") REFERENCES "trait"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_diseases_disease" ADD CONSTRAINT "FK_f44b728362ad3acdb4434a71e41" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_diseases_disease" ADD CONSTRAINT "FK_418a8fb4eeaefcf9c762f1cdaef" FOREIGN KEY ("diseaseId") REFERENCES "disease"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_addictions_addiction" ADD CONSTRAINT "FK_cf12cdf7300952d29ab46852c76" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_addictions_addiction" ADD CONSTRAINT "FK_588a0e8246203d8579a0de3d18d" FOREIGN KEY ("addictionId") REFERENCES "addiction"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_past_experiences_past_experience" ADD CONSTRAINT "FK_72286a7702cf4f22ba08c8837e6" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_past_experiences_past_experience" ADD CONSTRAINT "FK_746f5b48b27e8874231ce9e7d61" FOREIGN KEY ("pastExperienceId") REFERENCES "past_experience"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_factions_faction" ADD CONSTRAINT "FK_04c0fd053667adbdc11e8423567" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_factions_faction" ADD CONSTRAINT "FK_13d11465ba7c90a36ddc957f65e" FOREIGN KEY ("factionId") REFERENCES "faction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character_tags_tag" ADD CONSTRAINT "FK_dd444fc59bf0f731494ab1fe1d3" FOREIGN KEY ("characterId") REFERENCES "character"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "character_tags_tag" ADD CONSTRAINT "FK_f767c44fc839f4d53aedb2bd9fd" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "character_tags_tag" DROP CONSTRAINT "FK_f767c44fc839f4d53aedb2bd9fd"`);
        await queryRunner.query(`ALTER TABLE "character_tags_tag" DROP CONSTRAINT "FK_dd444fc59bf0f731494ab1fe1d3"`);
        await queryRunner.query(`ALTER TABLE "character_factions_faction" DROP CONSTRAINT "FK_13d11465ba7c90a36ddc957f65e"`);
        await queryRunner.query(`ALTER TABLE "character_factions_faction" DROP CONSTRAINT "FK_04c0fd053667adbdc11e8423567"`);
        await queryRunner.query(`ALTER TABLE "character_past_experiences_past_experience" DROP CONSTRAINT "FK_746f5b48b27e8874231ce9e7d61"`);
        await queryRunner.query(`ALTER TABLE "character_past_experiences_past_experience" DROP CONSTRAINT "FK_72286a7702cf4f22ba08c8837e6"`);
        await queryRunner.query(`ALTER TABLE "character_addictions_addiction" DROP CONSTRAINT "FK_588a0e8246203d8579a0de3d18d"`);
        await queryRunner.query(`ALTER TABLE "character_addictions_addiction" DROP CONSTRAINT "FK_cf12cdf7300952d29ab46852c76"`);
        await queryRunner.query(`ALTER TABLE "character_diseases_disease" DROP CONSTRAINT "FK_418a8fb4eeaefcf9c762f1cdaef"`);
        await queryRunner.query(`ALTER TABLE "character_diseases_disease" DROP CONSTRAINT "FK_f44b728362ad3acdb4434a71e41"`);
        await queryRunner.query(`ALTER TABLE "character_traits_trait" DROP CONSTRAINT "FK_4587390389294a489dd2986bf73"`);
        await queryRunner.query(`ALTER TABLE "character_traits_trait" DROP CONSTRAINT "FK_f94b5bf13399bf9da978917f9bf"`);
        await queryRunner.query(`ALTER TABLE "character_memory_pools_memory_pool" DROP CONSTRAINT "FK_90b4030407893812c08d19155d2"`);
        await queryRunner.query(`ALTER TABLE "character_memory_pools_memory_pool" DROP CONSTRAINT "FK_a249962a51899b420b63ce13ae0"`);
        await queryRunner.query(`ALTER TABLE "memory_facts_fact" DROP CONSTRAINT "FK_8c3179e191a3edde7594940ae1d"`);
        await queryRunner.query(`ALTER TABLE "memory_facts_fact" DROP CONSTRAINT "FK_8db0b9d2a2cd357ec77909ceee8"`);
        await queryRunner.query(`ALTER TABLE "tag_factions_faction" DROP CONSTRAINT "FK_4a2f5d9c7e82f8b9456dff32958"`);
        await queryRunner.query(`ALTER TABLE "tag_factions_faction" DROP CONSTRAINT "FK_e59c738f7a540c58078321d3167"`);
        await queryRunner.query(`ALTER TABLE "tag_facts_fact" DROP CONSTRAINT "FK_e59f64dd525be94f32cee86b4f3"`);
        await queryRunner.query(`ALTER TABLE "tag_facts_fact" DROP CONSTRAINT "FK_f9b3bc792d5168ac5960d3be6ca"`);
        await queryRunner.query(`ALTER TABLE "tag_effects_effect" DROP CONSTRAINT "FK_34f5cb09a55913c6f583bda3adc"`);
        await queryRunner.query(`ALTER TABLE "tag_effects_effect" DROP CONSTRAINT "FK_90f7534a5d05ee34893c6f008db"`);
        await queryRunner.query(`ALTER TABLE "tag_diseases_disease" DROP CONSTRAINT "FK_968cc66f706cd6c80bc0b9af44f"`);
        await queryRunner.query(`ALTER TABLE "tag_diseases_disease" DROP CONSTRAINT "FK_b65ac2bf7270d60ead58e5948c1"`);
        await queryRunner.query(`ALTER TABLE "tag_character_professions_character_profession" DROP CONSTRAINT "FK_d23da5f829aa85fb29cdae5e78d"`);
        await queryRunner.query(`ALTER TABLE "tag_character_professions_character_profession" DROP CONSTRAINT "FK_f4f942fcd8475de7d439483e106"`);
        await queryRunner.query(`ALTER TABLE "tag_characters_character" DROP CONSTRAINT "FK_27cabd722238a3ad436d21f5ec8"`);
        await queryRunner.query(`ALTER TABLE "tag_characters_character" DROP CONSTRAINT "FK_ba07cd68937697325925e117d10"`);
        await queryRunner.query(`ALTER TABLE "tag_traits_trait" DROP CONSTRAINT "FK_c3099a9a34ecc1e80b056ff9677"`);
        await queryRunner.query(`ALTER TABLE "tag_traits_trait" DROP CONSTRAINT "FK_8b1f9131098d4567bb35be25d63"`);
        await queryRunner.query(`ALTER TABLE "tag_skills_skill" DROP CONSTRAINT "FK_d46f32fb9e84e13d47545993945"`);
        await queryRunner.query(`ALTER TABLE "tag_skills_skill" DROP CONSTRAINT "FK_bbc0567f3d42c0d4da19f6120ef"`);
        await queryRunner.query(`ALTER TABLE "tag_memory_pools_memory_pool" DROP CONSTRAINT "FK_f27f02099bf1cff4297e544c872"`);
        await queryRunner.query(`ALTER TABLE "tag_memory_pools_memory_pool" DROP CONSTRAINT "FK_e1cbcaa49961df1ba43c725dc1e"`);
        await queryRunner.query(`ALTER TABLE "tag_memories_memory" DROP CONSTRAINT "FK_3c928dd23aa5b7d71aa3136a6b0"`);
        await queryRunner.query(`ALTER TABLE "tag_memories_memory" DROP CONSTRAINT "FK_90235abd5e059aabbeca65c4f28"`);
        await queryRunner.query(`ALTER TABLE "tag_character_memories_character_memory" DROP CONSTRAINT "FK_25f234875a96669139ff28aa54a"`);
        await queryRunner.query(`ALTER TABLE "tag_character_memories_character_memory" DROP CONSTRAINT "FK_b07d9250d6748cd3d32bb59ff7d"`);
        await queryRunner.query(`ALTER TABLE "tag_past_experiences_past_experience" DROP CONSTRAINT "FK_a8016f291bf0c652f47871ff16c"`);
        await queryRunner.query(`ALTER TABLE "tag_past_experiences_past_experience" DROP CONSTRAINT "FK_1dc46da1182ac79facb9ca9e585"`);
        await queryRunner.query(`ALTER TABLE "tag_items_item" DROP CONSTRAINT "FK_8e9c60c0a746da155dfe0c3a822"`);
        await queryRunner.query(`ALTER TABLE "tag_items_item" DROP CONSTRAINT "FK_6556352a2772efbe24fc2647bb2"`);
        await queryRunner.query(`ALTER TABLE "character_profession_memory_pools_memory_pool" DROP CONSTRAINT "FK_a6ec9345cfc82ffbd567c5ee8a6"`);
        await queryRunner.query(`ALTER TABLE "character_profession_memory_pools_memory_pool" DROP CONSTRAINT "FK_c663023d36c63c9940a21d8e2dc"`);
        await queryRunner.query(`ALTER TABLE "character_profession_characters_character" DROP CONSTRAINT "FK_a7ce4bf82a5166b7ba3d167acae"`);
        await queryRunner.query(`ALTER TABLE "character_profession_characters_character" DROP CONSTRAINT "FK_8a5ceae9e532cbb0ce61f170073"`);
        await queryRunner.query(`ALTER TABLE "skill_set" DROP CONSTRAINT "FK_d0d3cd62e50ac2fcd644dd1550f"`);
        await queryRunner.query(`ALTER TABLE "skill_set" DROP CONSTRAINT "FK_d0c8a9758fbae427159b634309e"`);
        await queryRunner.query(`ALTER TABLE "skill_set" DROP CONSTRAINT "FK_41da8f0493a6d068d595026d50e"`);
        await queryRunner.query(`ALTER TABLE "character_group_gen_instruction" DROP CONSTRAINT "FK_6d63ce23da5b9594f29bf9c1aa4"`);
        await queryRunner.query(`ALTER TABLE "character_group_gen_instruction" DROP CONSTRAINT "FK_1f4237c77fbce77d93bd236c294"`);
        await queryRunner.query(`ALTER TABLE "character_group_gen_instruction" DROP CONSTRAINT "FK_9087e620410a2b6886505e2dcc6"`);
        await queryRunner.query(`ALTER TABLE "character_gen_instruction" DROP CONSTRAINT "FK_49ebb0c49defe82560701a3be06"`);
        await queryRunner.query(`ALTER TABLE "character_gen_instruction" DROP CONSTRAINT "FK_fce68c3bb2d59205371302d37ea"`);
        await queryRunner.query(`ALTER TABLE "character_gen_instruction" DROP CONSTRAINT "FK_c5059610267d87105696173dace"`);
        await queryRunner.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_60328bf27019ff5498c4b977421"`);
        await queryRunner.query(`ALTER TABLE "campaign" DROP CONSTRAINT "FK_8e2dc400e55e237feba0869bc02"`);
        await queryRunner.query(`ALTER TABLE "campaign" DROP CONSTRAINT "FK_7607a0ed92ad0cc487086069a8f"`);
        await queryRunner.query(`ALTER TABLE "world" DROP CONSTRAINT "FK_5c6f20a4c309c357a2934164b5e"`);
        await queryRunner.query(`ALTER TABLE "activity_record" DROP CONSTRAINT "FK_7154b9208949faaf59c9559e3e3"`);
        await queryRunner.query(`ALTER TABLE "activity_record" DROP CONSTRAINT "FK_0f8f194a669e3c8b05dc8f9554b"`);
        await queryRunner.query(`ALTER TABLE "activity_record" DROP CONSTRAINT "FK_f3a947145cd73990b46f36bd661"`);
        await queryRunner.query(`ALTER TABLE "status" DROP CONSTRAINT "FK_fc6c49a4d23d0c792d52631f0bb"`);
        await queryRunner.query(`ALTER TABLE "status" DROP CONSTRAINT "FK_530cec77ca73dd3bc39b7d7b7f4"`);
        await queryRunner.query(`ALTER TABLE "status" DROP CONSTRAINT "FK_94cb5dda3cf592da917ec3a2746"`);
        await queryRunner.query(`ALTER TABLE "resistance" DROP CONSTRAINT "FK_735d519d3cf8c8a5d4f49e693d6"`);
        await queryRunner.query(`ALTER TABLE "resistance" DROP CONSTRAINT "FK_a7ae9428eab076395476966b0ea"`);
        await queryRunner.query(`ALTER TABLE "resistance" DROP CONSTRAINT "FK_16fb3bd7b74f585bb893a088209"`);
        await queryRunner.query(`ALTER TABLE "religion" DROP CONSTRAINT "FK_7144ce1861ab742646361527756"`);
        await queryRunner.query(`ALTER TABLE "religion" DROP CONSTRAINT "FK_1b805d14cbc9bf981aecb4e138c"`);
        await queryRunner.query(`ALTER TABLE "religion" DROP CONSTRAINT "FK_d9685bba5b8ec311605e6de213e"`);
        await queryRunner.query(`ALTER TABLE "personality_profile" DROP CONSTRAINT "FK_ad178fd7a19d09562d293af5f12"`);
        await queryRunner.query(`ALTER TABLE "personality_profile" DROP CONSTRAINT "FK_c31fd8278f85301590c66deab06"`);
        await queryRunner.query(`ALTER TABLE "personality_profile" DROP CONSTRAINT "FK_d5cc9f84863e90798509a241acb"`);
        await queryRunner.query(`ALTER TABLE "need" DROP CONSTRAINT "FK_4e9cef3d64e8ec4b4b9e8808001"`);
        await queryRunner.query(`ALTER TABLE "need" DROP CONSTRAINT "FK_fd881c0ba71e17dfb9eebdee61f"`);
        await queryRunner.query(`ALTER TABLE "need" DROP CONSTRAINT "FK_31b9dddb3ba04700bafa1ddc388"`);
        await queryRunner.query(`ALTER TABLE "mood" DROP CONSTRAINT "FK_f963136b0294ba43499ffb3dc1d"`);
        await queryRunner.query(`ALTER TABLE "mood" DROP CONSTRAINT "FK_bdcb2ca72fc62cbbf070be1992a"`);
        await queryRunner.query(`ALTER TABLE "mood" DROP CONSTRAINT "FK_063b678cbb2c84dfd95dff5da22"`);
        await queryRunner.query(`ALTER TABLE "item_set" DROP CONSTRAINT "FK_ea55fc163151757d1812bb142e6"`);
        await queryRunner.query(`ALTER TABLE "item_set" DROP CONSTRAINT "FK_2af689c42c21ec52fecf498edb1"`);
        await queryRunner.query(`ALTER TABLE "item_set" DROP CONSTRAINT "FK_b1c759d6706ebfc007af98ad4b3"`);
        await queryRunner.query(`ALTER TABLE "background" DROP CONSTRAINT "FK_514595bb7be1200882f61a58e71"`);
        await queryRunner.query(`ALTER TABLE "background" DROP CONSTRAINT "FK_3ca60c28267a0e7416b2ca11853"`);
        await queryRunner.query(`ALTER TABLE "background" DROP CONSTRAINT "FK_0b97b6d92d5cceb85ce6059e49a"`);
        await queryRunner.query(`ALTER TABLE "addiction" DROP CONSTRAINT "FK_72c3e468018000fec2fb7de15a8"`);
        await queryRunner.query(`ALTER TABLE "addiction" DROP CONSTRAINT "FK_b12bba127811e59ba1d457134d5"`);
        await queryRunner.query(`ALTER TABLE "addiction" DROP CONSTRAINT "FK_9c8cb34be63636f5df1c513fc90"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_73e8e485b0af5b70e156bdbf2d5"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_e65d0f0d18bac2d48aa3075ca7c"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_04c2fb52adfa5265763de8c4464"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_f18d5273f1ae641d654b8e11367"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_a7485d062b19695002b6175e8fb"`);
        await queryRunner.query(`ALTER TABLE "race" DROP CONSTRAINT "FK_3838011cae1fc347a263518fdaf"`);
        await queryRunner.query(`ALTER TABLE "race" DROP CONSTRAINT "FK_cf53c6c61bb2ee5c5cdc874e16f"`);
        await queryRunner.query(`ALTER TABLE "race" DROP CONSTRAINT "FK_c8a61aead3a0e005451152cb537"`);
        await queryRunner.query(`ALTER TABLE "birthsign" DROP CONSTRAINT "FK_b1199ea47fb769d1798555d35de"`);
        await queryRunner.query(`ALTER TABLE "birthsign" DROP CONSTRAINT "FK_2854aee8c563fb181a507e5631a"`);
        await queryRunner.query(`ALTER TABLE "birthsign" DROP CONSTRAINT "FK_2d767e0eba389143a97ace754c9"`);
        await queryRunner.query(`ALTER TABLE "character_memory" DROP CONSTRAINT "FK_41d2915bf350b5c29b1995d0330"`);
        await queryRunner.query(`ALTER TABLE "character_memory" DROP CONSTRAINT "FK_c2e1e6b2326c881926cce63883b"`);
        await queryRunner.query(`ALTER TABLE "character_memory" DROP CONSTRAINT "FK_03bc5aa08e9b1ffbf4fcc4bfd75"`);
        await queryRunner.query(`ALTER TABLE "character_memory" DROP CONSTRAINT "FK_e542b99701d4afa005afe285a82"`);
        await queryRunner.query(`ALTER TABLE "character_memory" DROP CONSTRAINT "FK_f13b49c601ff82b31ffc6e7f4fa"`);
        await queryRunner.query(`ALTER TABLE "memory" DROP CONSTRAINT "FK_4abb0599b000b0ce3dec5b17a53"`);
        await queryRunner.query(`ALTER TABLE "memory" DROP CONSTRAINT "FK_53a0f60ba10a56672e87dbaecb1"`);
        await queryRunner.query(`ALTER TABLE "memory" DROP CONSTRAINT "FK_fc71562e9a53841973da0dde326"`);
        await queryRunner.query(`ALTER TABLE "fact" DROP CONSTRAINT "FK_2d5fb22888c1e80aa08411bc922"`);
        await queryRunner.query(`ALTER TABLE "fact" DROP CONSTRAINT "FK_d0b06f4dfeec255770cf9976745"`);
        await queryRunner.query(`ALTER TABLE "fact" DROP CONSTRAINT "FK_6b6ea6cb2b2ac96f3c62cc63fab"`);
        await queryRunner.query(`ALTER TABLE "tag" DROP CONSTRAINT "FK_0c871deb494195392af68036e5a"`);
        await queryRunner.query(`ALTER TABLE "tag" DROP CONSTRAINT "FK_7e786468c032bf87daca95994f1"`);
        await queryRunner.query(`ALTER TABLE "tag" DROP CONSTRAINT "FK_d0dc39ff83e384b4a097f47d3f5"`);
        await queryRunner.query(`ALTER TABLE "faction" DROP CONSTRAINT "FK_1371bd66122552183eb1dd71672"`);
        await queryRunner.query(`ALTER TABLE "faction" DROP CONSTRAINT "FK_8d852638fb4e8c8adbea8410f8b"`);
        await queryRunner.query(`ALTER TABLE "faction" DROP CONSTRAINT "FK_4a708eed0751a8034015b18a607"`);
        await queryRunner.query(`ALTER TABLE "effect" DROP CONSTRAINT "FK_b09feadeed78b169d74a2194080"`);
        await queryRunner.query(`ALTER TABLE "effect" DROP CONSTRAINT "FK_eacae13387b50f668e1614c7734"`);
        await queryRunner.query(`ALTER TABLE "effect" DROP CONSTRAINT "FK_92fe6934186fd55be63731ebd4c"`);
        await queryRunner.query(`ALTER TABLE "disease" DROP CONSTRAINT "FK_cab8d6d8c256f68719a540aff5e"`);
        await queryRunner.query(`ALTER TABLE "disease" DROP CONSTRAINT "FK_9e2723c06088ac577a831b7204b"`);
        await queryRunner.query(`ALTER TABLE "disease" DROP CONSTRAINT "FK_d8fd3cb70b5e1ae39415bf97473"`);
        await queryRunner.query(`ALTER TABLE "trait" DROP CONSTRAINT "FK_dcccbe68509ea2fdf0596d15f8c"`);
        await queryRunner.query(`ALTER TABLE "trait" DROP CONSTRAINT "FK_2081978dfdc2941d78b00a339f3"`);
        await queryRunner.query(`ALTER TABLE "trait" DROP CONSTRAINT "FK_98b5a61037704fbae5012accc9f"`);
        await queryRunner.query(`ALTER TABLE "skill" DROP CONSTRAINT "FK_7625c2a421455904cb1fd4484c0"`);
        await queryRunner.query(`ALTER TABLE "skill" DROP CONSTRAINT "FK_e052e54357fbe0afca4605460b3"`);
        await queryRunner.query(`ALTER TABLE "skill" DROP CONSTRAINT "FK_c08612011a88745a32784544b28"`);
        await queryRunner.query(`ALTER TABLE "memory_pool" DROP CONSTRAINT "FK_a19c20c44be4479989c208d33ba"`);
        await queryRunner.query(`ALTER TABLE "memory_pool" DROP CONSTRAINT "FK_42665701f2d9ad130c0b334182f"`);
        await queryRunner.query(`ALTER TABLE "memory_pool" DROP CONSTRAINT "FK_1c9398af617de82b702fa43291e"`);
        await queryRunner.query(`ALTER TABLE "character_profession" DROP CONSTRAINT "FK_a24df76b4923bae1762434f3ae9"`);
        await queryRunner.query(`ALTER TABLE "character_profession" DROP CONSTRAINT "FK_66ed53e4c3526a9fd87374b4314"`);
        await queryRunner.query(`ALTER TABLE "character_profession" DROP CONSTRAINT "FK_56858e2c85bf45a6fa7fb699d2e"`);
        await queryRunner.query(`ALTER TABLE "memory_pool_entry" DROP CONSTRAINT "FK_47ac54fff26122aa2f8a1648549"`);
        await queryRunner.query(`ALTER TABLE "memory_pool_entry" DROP CONSTRAINT "FK_4a41d71a6dbadcb813692a520c6"`);
        await queryRunner.query(`ALTER TABLE "memory_pool_entry" DROP CONSTRAINT "FK_10613f49638aa623782d979013d"`);
        await queryRunner.query(`ALTER TABLE "memory_pool_entry" DROP CONSTRAINT "FK_5db0f5a08b1bc82b85b43f06570"`);
        await queryRunner.query(`ALTER TABLE "memory_pool_entry" DROP CONSTRAINT "FK_95ac39a7c5f9fab41fa9bd724ac"`);
        await queryRunner.query(`ALTER TABLE "past_experience" DROP CONSTRAINT "FK_403d570c9847f7e303e3c908463"`);
        await queryRunner.query(`ALTER TABLE "past_experience" DROP CONSTRAINT "FK_7073aac60002dbfdb42e0451973"`);
        await queryRunner.query(`ALTER TABLE "past_experience" DROP CONSTRAINT "FK_59d514d09b646b4aa3f2185d4e8"`);
        await queryRunner.query(`ALTER TABLE "item" DROP CONSTRAINT "FK_d4cce4776d3c0aa3ae2cea52d09"`);
        await queryRunner.query(`ALTER TABLE "item" DROP CONSTRAINT "FK_59ea1273219627c436037622fd7"`);
        await queryRunner.query(`ALTER TABLE "item" DROP CONSTRAINT "FK_5369db3bd33839fd3b0dd5525d1"`);
        await queryRunner.query(`ALTER TABLE "item" DROP CONSTRAINT "FK_3312c0e101d61169d3fdc075e11"`);
        await queryRunner.query(`ALTER TABLE "item" DROP CONSTRAINT "FK_fc4c2662a5b62d957af5a9793c5"`);
        await queryRunner.query(`ALTER TABLE "storage_slot" DROP CONSTRAINT "FK_0a24a514d42d95dd51640165de8"`);
        await queryRunner.query(`ALTER TABLE "storage_slot" DROP CONSTRAINT "FK_1b84d3566518cef431e04feaaee"`);
        await queryRunner.query(`ALTER TABLE "storage_slot" DROP CONSTRAINT "FK_3a645eb3e5dffeb6fc1efd532ff"`);
        await queryRunner.query(`ALTER TABLE "storage_slot" DROP CONSTRAINT "FK_1eb0325057d973a9c0e9531f20b"`);
        await queryRunner.query(`ALTER TABLE "equipment_slot" DROP CONSTRAINT "FK_9ffd83dbfdeedcaf88135efbb2a"`);
        await queryRunner.query(`ALTER TABLE "equipment_slot" DROP CONSTRAINT "FK_70883e6df724e96155c15b6af19"`);
        await queryRunner.query(`ALTER TABLE "equipment_slot" DROP CONSTRAINT "FK_669bbb6ed0d463595798c2f0b39"`);
        await queryRunner.query(`ALTER TABLE "equipment_slot" DROP CONSTRAINT "FK_9b36abbed55a1ba5a0d3e7ead50"`);
        await queryRunner.query(`ALTER TABLE "equipment_slot" DROP CONSTRAINT "FK_45a7d1e4c102ae58619b2e28b31"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f767c44fc839f4d53aedb2bd9f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd444fc59bf0f731494ab1fe1d"`);
        await queryRunner.query(`DROP TABLE "character_tags_tag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13d11465ba7c90a36ddc957f65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04c0fd053667adbdc11e842356"`);
        await queryRunner.query(`DROP TABLE "character_factions_faction"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_746f5b48b27e8874231ce9e7d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72286a7702cf4f22ba08c8837e"`);
        await queryRunner.query(`DROP TABLE "character_past_experiences_past_experience"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_588a0e8246203d8579a0de3d18"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf12cdf7300952d29ab46852c7"`);
        await queryRunner.query(`DROP TABLE "character_addictions_addiction"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_418a8fb4eeaefcf9c762f1cdae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f44b728362ad3acdb4434a71e4"`);
        await queryRunner.query(`DROP TABLE "character_diseases_disease"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4587390389294a489dd2986bf7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f94b5bf13399bf9da978917f9b"`);
        await queryRunner.query(`DROP TABLE "character_traits_trait"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90b4030407893812c08d19155d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a249962a51899b420b63ce13ae"`);
        await queryRunner.query(`DROP TABLE "character_memory_pools_memory_pool"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c3179e191a3edde7594940ae1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8db0b9d2a2cd357ec77909ceee"`);
        await queryRunner.query(`DROP TABLE "memory_facts_fact"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a2f5d9c7e82f8b9456dff3295"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e59c738f7a540c58078321d316"`);
        await queryRunner.query(`DROP TABLE "tag_factions_faction"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e59f64dd525be94f32cee86b4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9b3bc792d5168ac5960d3be6c"`);
        await queryRunner.query(`DROP TABLE "tag_facts_fact"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34f5cb09a55913c6f583bda3ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90f7534a5d05ee34893c6f008d"`);
        await queryRunner.query(`DROP TABLE "tag_effects_effect"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_968cc66f706cd6c80bc0b9af44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b65ac2bf7270d60ead58e5948c"`);
        await queryRunner.query(`DROP TABLE "tag_diseases_disease"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d23da5f829aa85fb29cdae5e78"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4f942fcd8475de7d439483e10"`);
        await queryRunner.query(`DROP TABLE "tag_character_professions_character_profession"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27cabd722238a3ad436d21f5ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba07cd68937697325925e117d1"`);
        await queryRunner.query(`DROP TABLE "tag_characters_character"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3099a9a34ecc1e80b056ff967"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b1f9131098d4567bb35be25d6"`);
        await queryRunner.query(`DROP TABLE "tag_traits_trait"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d46f32fb9e84e13d4754599394"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bbc0567f3d42c0d4da19f6120e"`);
        await queryRunner.query(`DROP TABLE "tag_skills_skill"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f27f02099bf1cff4297e544c87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1cbcaa49961df1ba43c725dc1"`);
        await queryRunner.query(`DROP TABLE "tag_memory_pools_memory_pool"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c928dd23aa5b7d71aa3136a6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90235abd5e059aabbeca65c4f2"`);
        await queryRunner.query(`DROP TABLE "tag_memories_memory"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25f234875a96669139ff28aa54"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b07d9250d6748cd3d32bb59ff7"`);
        await queryRunner.query(`DROP TABLE "tag_character_memories_character_memory"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8016f291bf0c652f47871ff16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1dc46da1182ac79facb9ca9e58"`);
        await queryRunner.query(`DROP TABLE "tag_past_experiences_past_experience"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e9c60c0a746da155dfe0c3a82"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6556352a2772efbe24fc2647bb"`);
        await queryRunner.query(`DROP TABLE "tag_items_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6ec9345cfc82ffbd567c5ee8a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c663023d36c63c9940a21d8e2d"`);
        await queryRunner.query(`DROP TABLE "character_profession_memory_pools_memory_pool"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7ce4bf82a5166b7ba3d167aca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a5ceae9e532cbb0ce61f17007"`);
        await queryRunner.query(`DROP TABLE "character_profession_characters_character"`);
        await queryRunner.query(`DROP TABLE "skill_set"`);
        await queryRunner.query(`DROP TABLE "character_group_gen_instruction"`);
        await queryRunner.query(`DROP TABLE "character_gen_instruction"`);
        await queryRunner.query(`DROP TYPE "public"."character_gen_instruction_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31ef2b4d30675d0c15056b7f6e"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c76f178c5065d1ab304b5832e"`);
        await queryRunner.query(`DROP TABLE "account"`);
        await queryRunner.query(`DROP TYPE "public"."account_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f0678ebd019c0ffcc5f60c78c"`);
        await queryRunner.query(`DROP TABLE "campaign"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cbb465c75a18296ce364ffdc8"`);
        await queryRunner.query(`DROP TABLE "world"`);
        await queryRunner.query(`DROP TABLE "activity_record"`);
        await queryRunner.query(`DROP TABLE "status"`);
        await queryRunner.query(`DROP TYPE "public"."status_type_enum"`);
        await queryRunner.query(`DROP TABLE "resistance"`);
        await queryRunner.query(`DROP TYPE "public"."resistance_effecttype_enum"`);
        await queryRunner.query(`DROP TABLE "religion"`);
        await queryRunner.query(`DROP TABLE "personality_profile"`);
        await queryRunner.query(`DROP TABLE "need"`);
        await queryRunner.query(`DROP TYPE "public"."need_layer_enum"`);
        await queryRunner.query(`DROP TYPE "public"."need_type_enum"`);
        await queryRunner.query(`DROP TABLE "mood"`);
        await queryRunner.query(`DROP TABLE "item_set"`);
        await queryRunner.query(`DROP TABLE "background"`);
        await queryRunner.query(`DROP TABLE "addiction"`);
        await queryRunner.query(`DROP TABLE "character"`);
        await queryRunner.query(`DROP TYPE "public"."character_gender_enum"`);
        await queryRunner.query(`DROP TABLE "race"`);
        await queryRunner.query(`DROP TABLE "birthsign"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1cf68b70d1f49512d8dda791d"`);
        await queryRunner.query(`DROP TABLE "character_memory"`);
        await queryRunner.query(`DROP TABLE "memory"`);
        await queryRunner.query(`DROP TYPE "public"."memory_type_enum"`);
        await queryRunner.query(`DROP TABLE "fact"`);
        await queryRunner.query(`DROP TABLE "tag"`);
        await queryRunner.query(`DROP TYPE "public"."tag_subtype_enum"`);
        await queryRunner.query(`DROP TABLE "faction"`);
        await queryRunner.query(`DROP TABLE "effect"`);
        await queryRunner.query(`DROP TYPE "public"."effect_element_enum"`);
        await queryRunner.query(`DROP TYPE "public"."effect_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."effect_target_enum"`);
        await queryRunner.query(`DROP TYPE "public"."effect_type_enum"`);
        await queryRunner.query(`DROP TABLE "disease"`);
        await queryRunner.query(`DROP TYPE "public"."disease_severity_enum"`);
        await queryRunner.query(`DROP TABLE "trait"`);
        await queryRunner.query(`DROP TYPE "public"."trait_traittype_enum"`);
        await queryRunner.query(`DROP TABLE "skill"`);
        await queryRunner.query(`DROP TYPE "public"."skill_category_enum"`);
        await queryRunner.query(`DROP TABLE "memory_pool"`);
        await queryRunner.query(`DROP TABLE "character_profession"`);
        await queryRunner.query(`DROP TABLE "memory_pool_entry"`);
        await queryRunner.query(`DROP TABLE "past_experience"`);
        await queryRunner.query(`DROP TYPE "public"."past_experience_exptype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6c7fa282dcacbfe6247b28f13"`);
        await queryRunner.query(`DROP TABLE "item"`);
        await queryRunner.query(`DROP TABLE "storage_slot"`);
        await queryRunner.query(`DROP TABLE "equipment_slot"`);
    }

}
