# Use Node.js base image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy only package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Avoid long installation times (CLEARLY ONLY FOR SLOPPY EARLY DEVELOPMENT ONLY)
COPY node_modules/ ./node_modules

# Install dependencies
RUN npm install

# Copy the rest of the code into the container
COPY src/ ./src

# Expose the gRPC server port
EXPOSE 50052

# Run migrations and start the gRPC server
CMD npm run start:dev