export enum D20_OUTCOME_ENUM {
    CRITICAL_FAILURE = "Critical Failure",
    STRONG_FAILURE = "Strong Failure",
    MILD_FAILURE = "Mild Failure",
    NEUTRAL_OUTCOME = "Neutral Outcome",
    MILD_SUCCESS = "Mild Success",
    STRONG_SUCCESS = "Strong Success",
    CRITICAL_SUCCESS = "Critical Success"
}

export enum D20_SCALE_TYPE_ENUM {
    LOW_RISK_LOW_IMPACT = "Low Risk Low Impact",
    LOW_RISK_MEDIUM_IMPACT = "Low Risk Medium Impact",
    LOW_RISK_HIGH_IMPACT = "Low Risk High Impact",
    MEDIUM_RISK_LOW_IMPACT = "Medium Risk Low Impact",
    MEDIUM_RISK_MEDIUM_IMPACT = "Medium Risk Medium Impact",
    MEDIUM_RISK_HIGH_IMPACT = "Medium Risk High Impact",
    HIGH_RISK_LOW_IMPACT = "High Risk Low Impact",
    HIGH_RISK_MEDIUM_IMPACT = "High Risk Medium Impact",
    HIGH_RISK_HIGH_IMPACT = "High Risk High Impact"
}




const D20_low_risk_low_impact_scale = {
    [D20_OUTCOME_ENUM.CRITICAL_FAILURE]: "1",
    [D20_OUTCOME_ENUM.STRONG_FAILURE]: null,
    [D20_OUTCOME_ENUM.MILD_FAILURE]: "2-3",
    [D20_OUTCOME_ENUM.NEUTRAL_OUTCOME]: "4-17",
    [D20_OUTCOME_ENUM.MILD_SUCCESS]: "18-19",
    [D20_OUTCOME_ENUM.STRONG_SUCCESS]: null,
    [D20_OUTCOME_ENUM.CRITICAL_SUCCESS]: "20"
};

const D20_medium_risk_low_impact_scale = {
    [D20_OUTCOME_ENUM.CRITICAL_FAILURE]: "1",
    [D20_OUTCOME_ENUM.STRONG_FAILURE]: "2",
    [D20_OUTCOME_ENUM.MILD_FAILURE]: "3-5",
    [D20_OUTCOME_ENUM.NEUTRAL_OUTCOME]: "6-15",
    [D20_OUTCOME_ENUM.MILD_SUCCESS]: "16-18",
    [D20_OUTCOME_ENUM.STRONG_SUCCESS]: "19",
    [D20_OUTCOME_ENUM.CRITICAL_SUCCESS]: "20"
};

const D20_high_risk_low_impact_scale = {
    [D20_OUTCOME_ENUM.CRITICAL_FAILURE]: "1-3",
    [D20_OUTCOME_ENUM.STRONG_FAILURE]: "4-6",
    [D20_OUTCOME_ENUM.MILD_FAILURE]: "7-10",
    [D20_OUTCOME_ENUM.NEUTRAL_OUTCOME]: "11-13",
    [D20_OUTCOME_ENUM.MILD_SUCCESS]: "14-17",
    [D20_OUTCOME_ENUM.STRONG_SUCCESS]: "18-19",
    [D20_OUTCOME_ENUM.CRITICAL_SUCCESS]: "20"
};



const D20_low_risk_medium_impact_scale = {
    [D20_OUTCOME_ENUM.CRITICAL_FAILURE]: "1",
    [D20_OUTCOME_ENUM.STRONG_FAILURE]: "2-3",
    [D20_OUTCOME_ENUM.MILD_FAILURE]: "4-6",
    [D20_OUTCOME_ENUM.NEUTRAL_OUTCOME]: "7-15",
    [D20_OUTCOME_ENUM.MILD_SUCCESS]: "16-18",
    [D20_OUTCOME_ENUM.STRONG_SUCCESS]: "19",
    [D20_OUTCOME_ENUM.CRITICAL_SUCCESS]: "20"
};

const D20_medium_risk_medium_impact_scale = {
    [D20_OUTCOME_ENUM.CRITICAL_FAILURE]: "1-3",
    [D20_OUTCOME_ENUM.STRONG_FAILURE]: "4-6",
    [D20_OUTCOME_ENUM.MILD_FAILURE]: "7-10",
    [D20_OUTCOME_ENUM.NEUTRAL_OUTCOME]: "11-13",
    [D20_OUTCOME_ENUM.MILD_SUCCESS]: "14-16",
    [D20_OUTCOME_ENUM.STRONG_SUCCESS]: "17-19",
    [D20_OUTCOME_ENUM.CRITICAL_SUCCESS]: "20"
};

const D20_high_risk_medium_impact_scale = {
    [D20_OUTCOME_ENUM.CRITICAL_FAILURE]: "1-5",
    [D20_OUTCOME_ENUM.STRONG_FAILURE]: "6-8",
    [D20_OUTCOME_ENUM.MILD_FAILURE]: "9-12",
    [D20_OUTCOME_ENUM.NEUTRAL_OUTCOME]: "13-14",
    [D20_OUTCOME_ENUM.MILD_SUCCESS]: "15-17",
    [D20_OUTCOME_ENUM.STRONG_SUCCESS]: "18-19",
    [D20_OUTCOME_ENUM.CRITICAL_SUCCESS]: "20"
};



const D20_low_risk_high_impact_scale = {
    [D20_OUTCOME_ENUM.CRITICAL_FAILURE]: "1",
    [D20_OUTCOME_ENUM.STRONG_FAILURE]: "2-3",
    [D20_OUTCOME_ENUM.MILD_FAILURE]: "4-6",
    [D20_OUTCOME_ENUM.NEUTRAL_OUTCOME]: "7-14",
    [D20_OUTCOME_ENUM.MILD_SUCCESS]: "15-18",
    [D20_OUTCOME_ENUM.STRONG_SUCCESS]: "19",
    [D20_OUTCOME_ENUM.CRITICAL_SUCCESS]: "20"
};

const D20_medium_risk_high_impact_scale = {
    [D20_OUTCOME_ENUM.CRITICAL_FAILURE]: "1-3",
    [D20_OUTCOME_ENUM.STRONG_FAILURE]: "4-6",
    [D20_OUTCOME_ENUM.MILD_FAILURE]: "7-10",
    [D20_OUTCOME_ENUM.NEUTRAL_OUTCOME]: "11-12",
    [D20_OUTCOME_ENUM.MILD_SUCCESS]: "13-16",
    [D20_OUTCOME_ENUM.STRONG_SUCCESS]: "17-19",
    [D20_OUTCOME_ENUM.CRITICAL_SUCCESS]: "20"
};

const D20_high_risk_high_impact_scale = {
    [D20_OUTCOME_ENUM.CRITICAL_FAILURE]: "1-5",
    [D20_OUTCOME_ENUM.STRONG_FAILURE]: "6-8",
    [D20_OUTCOME_ENUM.MILD_FAILURE]: "9-12",
    [D20_OUTCOME_ENUM.NEUTRAL_OUTCOME]: "13-14",
    [D20_OUTCOME_ENUM.MILD_SUCCESS]: "15-17",
    [D20_OUTCOME_ENUM.STRONG_SUCCESS]: "18-19",
    [D20_OUTCOME_ENUM.CRITICAL_SUCCESS]: "20"
};


export const D20_scales = {
    [D20_SCALE_TYPE_ENUM.LOW_RISK_LOW_IMPACT]: D20_low_risk_low_impact_scale,
    [D20_SCALE_TYPE_ENUM.LOW_RISK_MEDIUM_IMPACT]: D20_low_risk_medium_impact_scale,
    [D20_SCALE_TYPE_ENUM.LOW_RISK_HIGH_IMPACT]: D20_low_risk_high_impact_scale,
    [D20_SCALE_TYPE_ENUM.MEDIUM_RISK_LOW_IMPACT]: D20_medium_risk_low_impact_scale,
    [D20_SCALE_TYPE_ENUM.MEDIUM_RISK_MEDIUM_IMPACT]: D20_medium_risk_medium_impact_scale,
    [D20_SCALE_TYPE_ENUM.MEDIUM_RISK_HIGH_IMPACT]: D20_medium_risk_high_impact_scale,
    [D20_SCALE_TYPE_ENUM.HIGH_RISK_LOW_IMPACT]: D20_high_risk_low_impact_scale,
    [D20_SCALE_TYPE_ENUM.HIGH_RISK_MEDIUM_IMPACT]: D20_high_risk_medium_impact_scale,
    [D20_SCALE_TYPE_ENUM.HIGH_RISK_HIGH_IMPACT]: D20_high_risk_high_impact_scale
}