# Use Node.js base image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy only package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./



# Avoid long installation times (CLEARLY ONLY FOR SLOPPY EARLY DEVELOPMENT ONLY)
COPY node_modules/ ./node_modules



# Install dependencies
RUN npm install

# Copy the rest of the code into the container
COPY src/ ./src

# Copy world presets
COPY world_presets/ ./world_presets

COPY proto/ ./proto


# Expose the gRPC server port
EXPOSE 50051

# Start the gRPC server
# CMD ["sh", "-c", "npm run proto:generate && npm run start:dev"]
CMD ["sh", "-c", "npm run proto:generate && npm run migrate:generate && npm run migrate:run && npm run start:dev"]