"""Auto-update migration

Revision ID: 3b8627d776c5
Revises: 
Create Date: 2025-02-01 22:18:04.088704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8627d776c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('policy_group_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', name='providerenum'), nullable=False),
    sa.Column('model', sa.Enum('GPT_3_5_TURBO', 'GPT_4', 'GPT_4O', 'GPT_4O_MINI', name='aimodelenum'), nullable=False),
    sa.Column('input_token_limit', sa.Integer(), nullable=False),
    sa.Column('output_token_limit', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('DAILY', 'MONTHLY', 'YEARLY', name='policyperiodenum'), nullable=False),
    sa.ForeignKeyConstraint(['policy_group_id'], ['policy_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('policy_group_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['policy_group_id'], ['policy_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model', sa.Enum('GPT_3_5_TURBO', 'GPT_4', 'GPT_4O', 'GPT_4O_MINI', name='aimodelenum'), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', name='providerenum'), nullable=False),
    sa.Column('input_tokens_used', sa.Integer(), nullable=True),
    sa.Column('output_tokens_used', sa.Integer(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_usage_id'), 'user_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_usage_id'), table_name='user_usage')
    op.drop_table('user_usage')
    op.drop_table('users')
    op.drop_table('policies')
    op.drop_table('policy_groups')
    # ### end Alembic commands ###
