export enum DialogueOptionDirectionEnum {
    // General conversation flow
    ATTEMPT_TO_END_DIALOGUE = "ATTEMPT_TO_END_DIALOGUE",
    ATTEMPT_TO_CONTINUE_TOPIC = "ATTEMPT_TO_CONTINUE_TOPIC",
    ATTEMPT_TO_CHANGE_TOPIC_MINIMALLY = "ATTEMPT_TO_CHANGE_TOPIC_MINIMALLY",
    ATTEMPT_TO_CHANGE_TOPIC_SIGNIFICANTLY = "ATTEMPT_TO_CHANGE_TOPIC_SIGNIFICANTLY",

    // Emotional and tone control
    ATTEMPT_TO_CALM_COUNTERPART = "ATTEMPT_TO_CALM_COUNTERPART",
    ATTEMPT_TO_PROVOKE_COMBAT = "ATTEMPT_TO_PROVOKE_COMBAT",
    ATTEMPT_TO_CREATE_TENSION = "ATTEMPT_TO_CREATE_TENSION",
    ATTEMPT_TO_CREATE_HARMONY = "ATTEMPT_TO_CREATE_HARMONY",
    ATTEMPT_TO_FLATTER_COUNTERPART = "ATTEMPT_TO_FLATTER_COUNTERPART",
    ATTEMPT_TO_INSULT_COUNTERPART = "ATTEMPT_TO_INSULT_COUNTERPART",
    ATTEMPT_TO_AMUSE_COUNTERPART = "ATTEMPT_TO_AMUSE_COUNTERPART",
    ATTEMPT_TO_APOLOGIZE = "ATTEMPT_TO_APOLOGIZE",
    ATTEMPT_TO_GAIN_SYMPATHY = "ATTEMPT_TO_GAIN_SYMPATHY",

    // Motivations and goals
    ATTEMPT_TO_PURSUIT_PLAYER_GOALS = "ATTEMPT_TO_PURSUIT_PLAYER_GOALS",
    ATTEMPT_TO_DISTRACT_FROM_PLAYER_GOALS = "ATTEMPT_TO_DISTRACT_FROM_PLAYER_GOALS",
    ATTEMPT_TO_OBTAIN_INFORMATION = "ATTEMPT_TO_OBTAIN_INFORMATION",
    ATTEMPT_TO_SHARE_INFORMATION = "ATTEMPT_TO_SHARE_INFORMATION",
    ATTEMPT_TO_BARGAIN_OR_TRADE = "ATTEMPT_TO_BARGAIN_OR_TRADE",
    ATTEMPT_TO_SEEK_ALLIANCE = "ATTEMPT_TO_SEEK_ALLIANCE",
    ATTEMPT_TO_UNDERMINE_ALLIANCE = "ATTEMPT_TO_UNDERMINE_ALLIANCE",
    ATTEMPT_TO_GAIN_TRUST = "ATTEMPT_TO_GAIN_TRUST",
    ATTEMPT_TO_EXPLOIT_TRUST = "ATTEMPT_TO_EXPLOIT_TRUST",

    // Subterfuge and manipulation
    ATTEMPT_TO_LIE_AND_MANIPULATE = "ATTEMPT_TO_LIE_AND_MANIPULATE",
    ATTEMPT_TO_TELL_HALF_TRUTHS = "ATTEMPT_TO_TELL_HALF_TRUTHS",
    ATTEMPT_TO_CONFRONT_LIES = "ATTEMPT_TO_CONFRONT_LIES",
    ATTEMPT_TO_TRICK_OR_DECEIVE = "ATTEMPT_TO_TRICK_OR_DECEIVE",
    ATTEMPT_TO_EXPOSE_TRUTH = "ATTEMPT_TO_EXPOSE_TRUTH",

    // Conflict and combat
    ATTEMPT_TO_INITIATE_COMBAT = "ATTEMPT_TO_INITIATE_COMBAT",
    ATTEMPT_TO_DEFUSE_COMBAT = "ATTEMPT_TO_DEFUSE_COMBAT",
    ATTEMPT_TO_INTIMIDATE_COUNTERPART = "ATTEMPT_TO_INTIMIDATE_COUNTERPART",
    ATTEMPT_TO_CHALLENGE_COUNTERPART = "ATTEMPT_TO_CHALLENGE_COUNTERPART",

    // Social dynamics
    ATTEMPT_TO_ESTABLISH_DOMINANCE = "ATTEMPT_TO_ESTABLISH_DOMINANCE",
    ATTEMPT_TO_SUBMIT_TO_COUNTERPART = "ATTEMPT_TO_SUBMIT_TO_COUNTERPART",
    ATTEMPT_TO_FIND_COMMON_GROUND = "ATTEMPT_TO_FIND_COMMON_GROUND",
    ATTEMPT_TO_EXCLUDE_COUNTERPART = "ATTEMPT_TO_EXCLUDE_COUNTERPART",
    ATTEMPT_TO_INCLUDE_COUNTERPART = "ATTEMPT_TO_INCLUDE_COUNTERPART",

    // Moral alignment
    ATTEMPT_TO_APPEAL_TO_VIRTUE = "ATTEMPT_TO_APPEAL_TO_VIRTUE",
    ATTEMPT_TO_APPEAL_TO_VICE = "ATTEMPT_TO_APPEAL_TO_VICE",
    ATTEMPT_TO_ENCOURAGE_SELFISHNESS = "ATTEMPT_TO_ENCOURAGE_SELFISHNESS",
    ATTEMPT_TO_ENCOURAGE_SELFLESSNESS = "ATTEMPT_TO_ENCOURAGE_SELFLESSNESS",

    // Other creative options
    ATTEMPT_TO_TELL_A_STORY = "ATTEMPT_TO_TELL_A_STORY",
    ATTEMPT_TO_USE_HUMOR = "ATTEMPT_TO_USE_HUMOR",
    ATTEMPT_TO_USE_POETRY = "ATTEMPT_TO_USE_POETRY",
    ATTEMPT_TO_USE_RIDDLES = "ATTEMPT_TO_USE_RIDDLES",
    ATTEMPT_TO_USE_SILENCE = "ATTEMPT_TO_USE_SILENCE",
    ATTEMPT_TO_DIVERT_ATTENTION = "ATTEMPT_TO_DIVERT_ATTENTION",
}