# Use Node.js for building the app
FROM node:18 AS build

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

COPY public/ ./public
COPY src/ ./src

# Use a lightweight Node.js image to serve the app
FROM node:18

WORKDIR /usr/src/app
COPY --from=build /usr/src/app ./
EXPOSE ${FRONTEND_UI_PORT}

# Start the app
CMD ["npm", "run", "dev"]