# Use Node.js for building the app
FROM node:18 AS build

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

COPY public/ ./public
COPY src/ ./src

COPY proto/ ./proto

# Use a lightweight Node.js image to serve the app
FROM node:18
WORKDIR /usr/src/app
COPY --from=build /usr/src/app ./
EXPOSE 3000

# Start the app
CMD ["sh", "-c", "npm run proto:generate && npm run dev"]