export enum ActivityEventNameEnum {
    CONTENT_CREATED = "CONTENT_CREATED",
    CONTENT_UPDATED = "CONTENT_UPDATED",
    CONTENT_DELETED = "CONTENT_DELETED",
    CONTENT_CREATED_BULK = "CONTENT_CREATED_BULK",
    CONTENT_UPDATED_BULK = "CONTENT_UPDATED_BULK",
    CONTENT_DELETED_BULK = "CONTENT_DELETED_BULK",
    WORLD_PRESET_LOADED = "WORLD_PRESET_LOADED",
}