export enum RelationEnum {
    SPOUSE = "SPOUSE",
    SIBLING = "SIBLING",
    COUSIN = "COUSIN",
    PARENT = "PARENT",
    GRANDPARENT = "GRANDPARENT",
    DISTANT_RELATIVE = "DISTANT_RELATIVE",
    ACQUAINTANCE = "ACQUAINTANCE",
    FRIEND = "FRIEND",
    BEST_FRIEND = "BEST_FRIEND",
    RIVAL = "RIVAL",
    PARTNER = "PARTNER",
    NEIGHBOR = "NEIGHBOR",
}