export enum TagSubtypeEnum {
    MATERIAL = "MATERIAL",
    CULTURE = "CULTURE",
    RELATION = "RELATION",
    FACTION = "FACTION",
    RELIGION = "RELIGION",
    WEAPON_QUALITY = "WEAPON_QUALITY",
    ARMOR_QUALITY = "ARMOR_QUALITY",
    WEAPON_TYPE = "WEAPON_TYPE",
    STATUS = "STATUS",
    QUEST = "QUEST"
}