export enum TagSubtypeEnum {
    CULTURE = "CULTURE",
    RELATION = "RELATION",
    FACTION = "FACTION",
    RELIGION = "RELIGION",
    WEAPON_QUALITY = "WEAPON_QUALITY",
    ARMOR_QUALITY = "ARMOR_QUALITY",
}