export enum DialogueAttitudeEnum {
    ENTHUSIASTIC = 'ENTHUSIASTIC',
    FRIENDLY = 'FRIENDLY',
    NEUTRAL = 'NEUTRAL',
    RESERVED = 'RESERVED',
    RELUCTANT = 'RELUCTANT',
    SUSPICIOUS = 'SUSPICIOUS',
    PASSIVE_AGGRESSIVE = 'PASSIVE_AGGRESSIVE',
    HOSTILE = 'HOSTILE',
    DISRESPECTFUL = 'DISRESPECTFUL',
    FEARFUL = 'FEARFUL',
    ADMIRING = 'ADMIRING',
    DISMISSIVE = 'DISMISSIVE',
    CURIOUS = 'CURIOUS',
    CONDESCENDING = 'CONDESCENDING',
    DEFERENTIAL = 'DEFERENTIAL'
}