export enum DICE_OUTCOME_ENUM {
    CRITICAL_FAILURE = "CRITICAL_FAILURE",
    STRONG_FAILURE = "STRONG_FAILURE",
    MILD_FAILURE = "MILD_FAILURE",
    NEUTRAL_OUTCOME = "NEUTRAL_OUTCOME",
    MILD_SUCCESS = "MILD_SUCCESS",
    STRONG_SUCCESS = "STRONG_SUCCESS",
    CRITICAL_SUCCESS = "CRITICAL_SUCCESS"
}
