export enum DICE_OUTCOME_ENUM {
    DICE_OUTCOME_CRITICAL_FAILURE = "DICE_OUTCOME_CRITICAL_FAILURE",
    DICE_OUTCOME_STRONG_FAILURE = "DICE_OUTCOME_STRONG_FAILURE",
    DICE_OUTCOME_MILD_FAILURE = "DICE_OUTCOME_MILD_FAILURE",
    DICE_OUTCOME_NEUTRAL_OUTCOME = "DICE_OUTCOME_NEUTRAL_OUTCOME",
    DICE_OUTCOME_MILD_SUCCESS = "DICE_OUTCOME_MILD_SUCCESS",
    DICE_OUTCOME_STRONG_SUCCESS = "DICE_OUTCOME_STRONG_SUCCESS",
    DICE_OUTCOME_CRITICAL_SUCCESS = "DICE_OUTCOME_CRITICAL_SUCCESS"
}
