export enum SCALE_RISK_IMPACT_ENUM {
    LOW_RISK_LOW_IMPACT = "LOW_RISK_LOW_IMPACT",
    LOW_RISK_MEDIUM_IMPACT = "LOW_RISK_MEDIUM_IMPACT",
    LOW_RISK_HIGH_IMPACT = "LOW_RISK_HIGH_IMPACT",
    MEDIUM_RISK_LOW_IMPACT = "MEDIUM_RISK_LOW_IMPACT",
    MEDIUM_RISK_MEDIUM_IMPACT = "MEDIUM_RISK_MEDIUM_IMPACT",
    MEDIUM_RISK_HIGH_IMPACT = "MEDIUM_RISK_HIGH_IMPACT",
    HIGH_RISK_LOW_IMPACT = "HIGH_RISK_LOW_IMPACT",
    HIGH_RISK_MEDIUM_IMPACT = "HIGH_RISK_MEDIUM_IMPACT",
    HIGH_RISK_HIGH_IMPACT = "HIGH_RISK_HIGH_IMPACT"
}